### ISSUE TITLE
[FEATURE REQUEST] Expand benchmark table content to always include % diff

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#101]
Most GEOS-Chem benchmark tables include ref value, dev value, difference, and % difference. However, some omit % difference. It would be useful for quick validation if % difference was always included in addition to absolute difference. 

This impacts Emissions_totals.txt and Inventory_totals.txt for the 1-month full chemistry benchmark. I have not evaluated if it impacts any tables generated specifically for the 1-year full chemistry or 1-year transport tracer benchmarks.

**Comment by msulprizio** [comment]
I second this. Looking through the benchmark results for 13.0.0, it would be extremely useful to have a column for % difference in the Emission_totals.txt and Inventory_totals.txt files.

**Comment by msulprizio** [comment]
This is now resolved in commit https://github.com/geoschem/gcpy/commit/7bb95b32627cd70f1f6954b7e80b340019bd7230.
