### ISSUE TITLE
[BUG/ISSUE] file_regrid does not work on a dataset that is only 1 level

### ISSUE THREAD

**Issue by jmoch1214** [geoschem/gcpy#105]
## Describe the bug

I'm trying to regrid a c48 GCHP output file of just hourly surface ozone concentrations to a 2x2.5 lat-lon grid, but I keep getting an error. The dimensions of the GCHP output file I want to regard are: "Xdim: 48; Ydim: 48; lev: 1; nf: 6; time: 744"

## To Reproduce
List the steps to reproduce the bug or issue below:

I try using the following lines of code after loading GCPy (used on Cannon)

```python
save_dir='/net/seasasfs02/srv/export/seasasfs02/share_root/jmoch/geoE_dat/combined_output/hourly_combined/'
sim ='geoE'
MN='01'
path_load = savedir+sim+'.Health_hr.avg_MN'+MN+'_SpeciesConc_O3.nc4'
path_save = savedir+sim+'.Health_hr.avg_MN'+MN+'_SpeciesConc_O3_2x25.nc4'

gcpy.file_regrid(fin=path_load,fout=path_save,dim_format_in='diagnostic',dim_format_out='classic',ll_res_out='2x25')
```

The error message is:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-75-06186904b3cb> in <module>
      9 path_save = savedir+sim+'.Health_hr.avg_MN'+MN+'_SpeciesConc_O3_2x25.nc4'
     10 
---> 11 gcpy.file_regrid(fin=path_load,fout=path_save,dim_format_in='diagnostic',dim_format_out='classic',ll_res_out='2x25')
     12 
     13 # gcpy.make_regridder_C2L(csres_in='48',llres_out='2x25')

~/.conda/envs/gcpy_env/lib/python3.7/site-packages/gcpy/file_regrid.py in file_regrid(fin, fout, dim_format_in, dim_format_out, cs_res_out, ll_res_out, sg_params_in, sg_params_out)
    188         ds_out = drop_and_rename_classic_vars(ds_out, towards_gchp=False)
    189         ds_out = ds_out.reindex(lev=ds_out.lev[::-1])
--> 190         _, lev_coords, _ = get_vert_grid(ds_out)
    191         ds_out = ds_out.assign_coords({'lev': lev_coords})
    192         ds_out['lat'].attrs = {'long_name': 'Latitude',

~/.conda/envs/gcpy_env/lib/python3.7/site-packages/gcpy/grid.py in get_vert_grid(dataset, AP, BP)
    280             "as keyword arguments")
    281     else:
--> 282         new_grid = vert_grid(AP, BP)
    283         return new_grid.p_edge(), new_grid.p_mid(), np.size(AP)
    284 

~/.conda/envs/gcpy_env/lib/python3.7/site-packages/gcpy/grid.py in __init__(self, AP, BP, p_sfc)
    387 class vert_grid:
    388     def __init__(self, AP=None, BP=None, p_sfc=1013.25):
--> 389         if (AP.size != BP.size) or (AP is None):
    390             # Throw error?
    391             print('Inconsistent vertical grid specification')

AttributeError: 'list' object has no attribute 'size'
```

## Expected behavior
it should regrid the file and give me a single level 2x2.5 grided version of the GCHP output

## Required information:
I got an error when trying to do this:
```python
>>> import gcpy
>>> gcpy.show_versions()
```
The error was:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-81-7d6c91148452> in <module>
      1 import gcpy
----> 2 gcpy.show_versions()

AttributeError: module 'gcpy' has no attribute 'show_versions'
```

## Additional context
Provide any other context about the problem here.

[The readthedocs says](https://gcpy.readthedocs.io/en/latest/Regridding.html), "GCPy automatically handles regridding between different vertical grids when plotting except when you pass a dataset that is not on the typical 72-level or 47-level vertical grids. If using a different vertical grid, you will need to pass the corresponding grid parameters using the ref_vert_params or dev_vert_params keyword arguments."  However, there are ref_vert_params and dev_vert_params are not valid keywords for file_regrid.

**Comment by WilliamDowns** [comment]
Thanks for reporting this Jonathan. I've pushed [a fix to automate CS->LL regridding for 1-level files](https://github.com/geoschem/gcpy/commit/9c794600fd8f7b1b149e6c54a1672b54e3d4be2d) to the `dev/1.0.1` branch, which unfortunately is not available on Conda yet. The fastest way to get those changes would probably be to clone the GCPy repo, checkout the remote `dev/1.0.1` branch, run `conda uninstall geoschem-gcpy` from your Conda environment, `cd` into your clone of GCPy, and execute `pip install -e .`. Also FYI your call to `file_regrid()` should say `ll_res_out='2x2.5'` (right now you're calling for a 2 by 25 degree grid).

**Comment by jmoch1214** [comment]
thanks @WilliamDowns. This appears to have fixed the issue for me.
