### ISSUE TITLE
[BUG/ISSUE] Can't install GCPy via Anaconda "PackagesNotFound" Error. 

### ISSUE THREAD

**Issue by jdhask** [geoschem/gcpy#108]
## Describe the bug
[Following the documentation]([https://gcpy.readthedocs.io/en/stable/Getting-Started-with-GCPy.html), I was trying to install gcpy with all its dependencies via an Anaconda terminal on Windows 10, python version=3.7.0 in a brand new environment (and in a different environment with python 3.8.7), but in both instances, I got the error "PackagesNotFound: The following packages are not available from current channels: -gcpy". 

## To Reproduce
Make a new environment, and make sure we have a conda-forge channel: 
```python
conda create -n gcpy_env
conda activate gc_py_env
conda config --add channels conda-forge
```
I tried a few different lines to install, based on differing instructions, but both failed in the same error of "Packages Not Found". 
```python
conda install -c conda-forge geoschem-gcpy
conda install geoschem-gcpy
```
## Expected behavior
I expected the package to install. 

## Required information:
Here's a screenshot of my calls and the error.  It doesn't look like its a conda-forge channel error, but rather a gcpy error, though their interactions are a bit above my python knowledge.  
![image](https://user-images.githubusercontent.com/46688499/107671166-8a215580-6c61-11eb-8b8a-35a04e94d97f.png)

## Additional context
I was going to work in a clone, but I kept having to install dependencies when I discovered that the full install wasn't working.

**Comment by WilliamDowns** [comment]
Hi Jessica, unfortunately GCPy through conda-forge is definitely not currently available on Windows because ESMPy (a dependency of xESMF, which is itself a dependency of GCPy) is not available for Windows through Anaconda. It's unclear if ESMPy is functional on Windows at all at the moment, even if you were to build it manually from source. We will update the GCPy documentation to make it clear that Windows is not currently available. Sorry for the inconvenience.

**Comment by jdhask** [comment]
, I just got around to trying to install esmpy as a dependency myself and noticed that as well. I'll try again on our linux machine.

**Comment by WilliamDowns** [comment]
Documentation updated in  [https://github.com/geoschem/gcpy/commit/52e65385c60e9562f225a4778d4e4c5d480ef934](https://github.com/geoschem/gcpy/commit/52e65385c60e9562f225a4778d4e4c5d480ef934).
