### ISSUE TITLE
[FEATURE REQUEST] Flexible filename timestamps in benchmark scripts

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#114]
The most recent version of MAPL has a monthly time-averaged diagnostic option for collections in `HISTORY.rc`. However, unlike time-averaged diagnostics generated using the `Frequency` field which include averaging period _mid-point_ in filename, the monthly diagnostics include the averaging period _start_. Moving from our current practice of 12 consecutive 1-month runs for 1-year benchmarks to using the monthly diagnostics will therefore break the benchmarking scripts.

This feature request is for the option to use either mid-point or start date-time in GCHP filenames for benchmarking. A simple toggle in the benchmark scripts would allow using time-averaged diagnostics generated using either method. This will allow easily adapting the scripts to compare time-averaged files other than monthly, and also allow changing our 1-year benchmarking to using monthly output of a continuous run.

**Comment by lizziel** [comment]
I now have MAPL updates from GMAO to output GCHP diagnostic files with time-averaging period start time. We can now output GCHP diagnostics with the same filenames at GEOS-Chem Classic. I will tackle this GCPy feature request to coincide with changing the default diagnostic filenames. Having the ability to use either mid-point or start for ref or dev is necessary for benchmarking and comparing with older versions of GCHP.

**Comment by yantosca** [comment]
This option could eventually be selected in a YAML configuration file, such as is proposed in #117.

**Comment by lizziel** [comment]
Yes, and at some point we can exclude specifying it at all since the new filename format would be default for many versions in a row. I implemented it as an optional argument. I'm still testing so haven't pushed yet.

**Comment by lizziel** [comment]
The option for start or mid-point time in GCHP filename is now available in GCPy.
