### ISSUE TITLE
[DISCUSSION] Timing tool for GC-Classic and GCHP

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#116]
Right now timing info is printed to GC-Classic and GCHP logs but we don't have a tool to scrape it and put it in a nice format. This could be added to GCPy and run automatically during benchmarks. This discussion is to evaluate what we would want to include in the design. Once we've decided on design it can be made into a feature request.

Here are some things that I think would be useful:
-Flexibility to scrape timing info from one, or two, or many logs at once. If two then a ref vs dev comparison would be generated. Otherwise the data would just be nicely formatted in a text file.
-Option to convert time units to something other than seconds
-Capability to produce a simple figure of some sort with time comparison by component if given more than one log.

Please add you thoughts and ideas!

**Comment by LiamBindle** [comment]
This is a great idea. It would be nice automatically track differences in wall time between minor/major versions, so we can keep an eye on it over time.

I think the features mentioned above cover things nicely. A command line interface (tool) to the parser would be useful too.

**Comment by yantosca** [comment]
I agree, this could be a very useful tool.  We can use the numpy.datetime class to convert times from seconds pretty easily.  This would really help identify bottlenecks.
