### ISSUE TITLE
[FEATURE REQUEST] Use a YAML file to define configurable settings for benchmark scripts

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#117]
Currently all of the configurable settings in the benchmark driver scripts:

  * run_1mo_benchmark.py
  * run_1yr_fullchem_benchmark.py
  * run_1yr_tt_benchmark.py

have to be hard-coded by editing Python variable definitions.  It would be a useful feature to have all configurables contained in a YAML file (similar to examples/diagnostics/compare_diags.py in GCPy 1.0.4 and later -- currently in development at the time of this writing).  

This can be done in conjunction with Feature Request #102, which would seek to abstract reusable code from the benchmark scripts into functions.

**Comment by laestrada** [comment]
Addressed in #133
