### ISSUE TITLE
[BUG/ISSUE] compare_zonal_mean flip_ref and flip_dev not working as expected

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#12]
When comparing GCHP internal state output (checkpoint file) I use flip_ref and flip_dev to flip the vertical axis for zonal mean plots using compare_zonal_mean. It appears that it has no effect, however, and the plots show concentrations that are incorrect with respect to the y-axis. 

For example, here is the correctly plotted SpeciesConc collection zonal mean for H2O, which does not require flipping.

<img width="789" alt="SpeciesConc_H2O_ZM" src="https://user-images.githubusercontent.com/651947/63124518-78ca9080-bf79-11e9-90ea-932c4799f649.png">

In contrast, here is the internal restart file zonal mean for H2O:

<img width="753" alt="SPC_H2O_ZM" src="https://user-images.githubusercontent.com/651947/63124720-f1315180-bf79-11e9-9af7-a773e84d664a.png">

To reproduce the issue, use compare_zonal_mean function with GCHP checkpoint files (gcchem*) and pass arguments flip_ref=True and flip_dev=True in one case, and default values (False) in another. If the resulting plots are the same then flip_ref and flip_dev do not work as expected.

Expected behavior: passing flip_ref and flip_dev as True to compare_zonal_mean should result in vertically flipping relative to not passing them. The zonal mean should resemble the SpeciesConc collection zonal mean.

This issue has gone under the radar since we do not benchmark GCHP restart files and the only History collection that is vertically flipped is emissions which we do not generate zonal mean plots for.

**Comment by yantosca** [comment]
I have pushed commit https://github.com/geoschem/gcpy/commit/17b318a0b84d40fc6f4ed2acdbf19330212eeaba, which I believe now resolves this issue.

In routine compute_zonal_mean, if both flip_ref=True and flip_dev=True, a typo caused Ref to be flipped, and then flipped back again to its initial level ordering.  This has now been fixed.

Calling compute_zonal_mean to plot the SPC_H2O field of a GCHP restart file, with arguments flip_ref=True and flip_dev=True now results in a plot that looks much more like SpeciesConc_H2O:

![flip](https://user-images.githubusercontent.com/5880296/64201098-d73dad00-ce5b-11e9-9479-e1ac7f85eb20.png)
