### ISSUE TITLE
[QUESTION]How to use gcpy.plot

### ISSUE THREAD

**Issue by Zhongci96** [geoschem/gcpy#124]
## Type your question below:
I installed the GCPY library on macOS using Conda
There are no errors in import copy
But I can't use the "import gcpy.plot" function
How can I solve this problem？

<img width="1265" alt="WeChat32337019c37f083b551afd4a11b2f05f" src="https://user-images.githubusercontent.com/83695000/122584896-78c3dc00-d08d-11eb-82fc-ee2e5b618378.png">

**Comment by lizziel** [comment]
Hi @Zhongci96, were you able to resolve this issue?
