### ISSUE TITLE
How to make a full extent plot using the re-gridded output array from "Sparselt"?

### ISSUE THREAD

**Issue by SadiaAfrin9888** [geoschem/gcpy#135]
## Type your question below:
Hi, I am using the "Sparselt" library to regrid the GCHP output data into a 2x2.5 degree regular grid. The output array looks like:

`<xarray.Dataset>
Dimensions:         (time: 1, lev: 1, lat: 91, lon: 144)
Dimensions without coordinates: time, lev, lat, lon
Data variables:
    SpeciesConc_O3  (time, lev, lat, lon) float64 2.375e-08 ... 1.908e-08 `

Then,  I was trying to use gcpy ("gcplot.compare_single_level(ds3['SpeciesConc_O3'].isel(lev=0), title='Re Surface Ozone over the North Pacific')") command to plot this re-gridded 2x2.5 degree array. Also, repeat the process to get a 4x5 degree array. The maps look like:
[gcpy.pdf](https://github.com/geoschem/gcpy/files/7443644/gcpy.pdf)

However, it looks like for the '2x2.5' degree array, gcpy is plotting a chunk of the entire globe from 0-144E and 0-91N, and for the  '4x5' degree array, gcpy is plotting a chunk of the entire globe from 0-72E and 0-46N. I have tried to define the extent by adding  extent=[-180,180,-90,90], and also tried with other extents. For any case, I am not getting the full extent of global plot, and getting the error message that 
"ValueError: arguments without labels along dimension "lat' cannot be aligned because they have different dimension sizes:{90,91}"

I would appreciate it if you can help me in this regard. Thanks.

Sadia

**Comment by laestrada** [comment]
Hi @SadiaAfrin9888,

Thanks for writing in. Based on your output array, it looks like the issue might be how you are regridding your output data with the sparseit library. The lat and lon dimensions you posted above suggest that the 0-144E and 0-91N chunk is the size of the regridded dataset. 

Additionally, [compare_single_level](https://gcpy.readthedocs.io/en/stable/Plotting.html#compare-single-level) has 4 required arguments (`refdata, refstr, devdata, devstr`), above it looks like you are only passing in one -- is that true?

**Comment by SadiaAfrin9888** [comment]
Hi,
Thanks for your reply. Basically, I am using the following commands to regrid:

`gridspec-create gcs 24
gridspec-create latlon 91 144 -pc -dc
ESMF_RegridWeightGen -s c24_gridspec.nc -d regular_lat_lon_91x144.nc -m conserve -w esmf_regrid_weights_c24_to_latlon91x144.nc --tilefile_path /home/safrin/Python/

transform = sparselt.esmf.load_weights(
    'esmf_regrid_weights_c24_to_latlon91x144.nc',                               # Generated by ESMF_RegridWeightGen
    input_dims=[('nf', 'Ydim', 'Xdim'), (6, 24, 24)],  # applied along input dimensions
    output_dims=[('lat', 'lon'), (91, 144)],           # result dimensions
)

ds0 = xr.open_dataset('trial.nc') 
ds= ds0.drop(['nf', 'Ydim', 'Xdim', 'ncontact', 'contacts', 'orientation', 'anchor', 'corner_lons', 'corner_lats', 'lev', 'time', 'cubed_sphere'])
ds = sparselt.xr.apply(transform, ds)
`


I am attaching the 'regular lat lon', 'C24_grid' and the "esmf_weight" files, I used for regridding, for your consideration. 
[c24_gridspec.nc.pdf](https://github.com/geoschem/gcpy/files/7461161/c24_gridspec.nc.pdf)
[regular_lat_lon_91x144.nc.pdf](https://github.com/geoschem/gcpy/files/7461162/regular_lat_lon_91x144.nc.pdf)
[esmf_regrid_weights_c24_to_latlon91x144.nc.pdf](https://github.com/geoschem/gcpy/files/7461163/esmf_regrid_weights_c24_to_latlon91x144.nc.pdf)

For the plotting, I actually used the single_panel() command, not the compare_single_level. I mentioned ''compare_single_level" by mistake. 

I would highly appreciate it if you could have a look at the files. Thanks for your continuous support.

**Comment by laestrada** [comment]
Hi @SadiaAfrin9888,

Thanks for posting the above files. Could you also post your `trial.nc` file as well so I can try it out on my end? It looks like you should be setting `output_dims=[('lat', 'lon'), (90, 180)]` instead of 91, 144. However, I am not overly familiar with sparselt -- tagging @LiamBindle to see if he will weigh in.

**Comment by LiamBindle** [comment]
Thanks for tagging me, I didn't see this.

@SadiaAfrin9888 I believe you regridded your dataset correctly, but the problem is the output of `sparselt.xr.apply(transform, ds)` is a naked dataset. Specifically, `lat` and `lon` are indices, they aren't actually latitude and longitude coordinates. 

There is an optional keyword argument to `sparselt.xr.apply` that allows you to specify a "template" dataset. Cutting to the chase, you should be able to use 'regular_lat_lon_91x144.nc' as your "template dataset". That will bootstrap the latitude and longitude coordinates into your output dataset, which should then work okay with GCPy or other tools. 

Does this work?
```python

# Open input dataset and drop everything that doesn't have the correct "input_dims"
ds0 = xr.open_dataset('trial.nc')
ds= ds0.drop(['nf', 'Ydim', 'Xdim', 'ncontact', 'contacts', 'orientation', 'anchor', 'corner_lons', 'corner_lats', 'lev', 'time', 'cubed_sphere'])

# Open a template dataset for bootstrapping coordinates like latitude/longitude, etc.
output_template = xr.open_dataset('regular_lat_lon_91x144.nc')

# Apply the transform 
ds = sparselt.xr.apply(transform, ds, output_dataset_template=output_template)
```

**Comment by LiamBindle** [comment]
Also, here is an example of using the `output_dataset_template` argument: https://github.com/LiamBindle/sparselt/blob/master/examples/esmf_regrid_example.py.

If you have any troubles, if you share 'trial.nc' I can have a go at it.

**Comment by SadiaAfrin9888** [comment]
Hi, @LiamBindle, thank you so much. Defining the "output_dataset_template" solves the problem. I highly appreciate your support.

Hi @laestrada, thanks for your concern. The problem is now solved.

**Comment by LiamBindle** [comment]
@SadiaAfrin9888 Awesome! Happy to help!
