### ISSUE TITLE
[QUESTION] Different result using single panel and compare single level

### ISSUE THREAD

**Issue by thng0526** [geoschem/gcpy#138]
## Describe the bug
I finished two simulations in GCHP and want to compare the output. However, the plots using `single_panel` look fine while they all look weird with `compare_single_level`. I wonder if there is anything I missed in `compare_single_level`, or it is a bug. Thanks for your help.

reference plot (no fire emission):
![201008 Global concentration of carbon monoxide on surface level (no fire)](https://user-images.githubusercontent.com/57167249/148916825-d1c80383-4f1b-41ed-a6c9-fe7fcdeddf69.png)

development plot (GFED fire emission):
![201008 Global concentration of carbon monoxide on surface level](https://user-images.githubusercontent.com/57167249/148916895-0d3e54a6-f141-4457-92ef-4d273fc195df.png)

`compare_single_level` plot
![image](https://user-images.githubusercontent.com/57167249/148916729-5ebbf7c2-5315-4ca4-808c-23fc4440d980.png)

## To Reproduce
List the steps to reproduce the bug or issue below:
This is my python script for `compare_single_level`.
[Compare_single_level.txt](https://github.com/geoschem/gcpy/files/7845328/Compare_single_level.txt)

I can't upload the nc files here. Feel free to ask me if you want to take a look on the data file.

## Expected behavior
I guess it is related with the unit conversion (or matching in `compare_single_level`)

## Required information:
I can't print the versions of my GCPY but I can use it with conda. 

(gcpy_env) tsinhungng@Tsins-Mac-mini ~ % python
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 20:33:18) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gcpy
>>> gcpy.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gcpy' has no attribute 'show_versions'
>>> 

## Additional context
Provide any other context about the problem here.

**Comment by lizziel** [comment]
Hi @thng0526, if you got GCPy via conda you should be able to do `conda list gcpy` to display GCPy version.

**Comment by thng0526** [comment]
Thanks @lizziel. Here are the version list.

> # packages in environment at /opt/anaconda3/envs/gcpy_env:
> #
> # Name                    Version                   Build  Channel
> geoschem-gcpy             1.1.0            py39h6e9494a_0    conda-forge

**Comment by lizziel** [comment]
Hi @thng0526, were you able to resolve this issue? That is the latest version of GCPy and I don't see any bug fixes added related to compare_single_level since the release. Is there a way for you to share the netcdf file so we can try to reproduce?

**Comment by thng0526** [comment]
Hi @lizziel, I still can't resolve the issue. Would it be good if I send you the netcdf file through email to this address 'elundgren@seas.harvard.edu'?

**Comment by lizziel** [comment]
The files might be too big to send over email. Is it possible for you put on Dropbox or a similar platform for me to download?

**Comment by thng0526** [comment]
I had uploaded the scripts and those .nc files to OneDrive. You may download using the link below. Thanks.

https://mycuhk-my.sharepoint.com/:f:/g/personal/1155063422_link_cuhk_edu_hk/EjxxQJ6RhENEoFAhQIMI2mkBBwidsXtkl2iE-W6MdB38wQ?e=g96pLC

**Comment by lizziel** [comment]
Thanks @thng0526. I indeed see strange things with your data when viewing with GCPy function compare_single_level. I also viewed with Panoply and noticed it looks like you generated the data with stretched grid given the image below. 

<img width="1041" alt="Screen Shot 2022-02-16 at 12 29 24 PM" src="https://user-images.githubusercontent.com/651947/154323830-a50812d0-4a5c-4209-a5cb-78f4d5958c99.png">

For non-stretched grid data files the faces are shown like this instead:

<img width="1071" alt="Screen Shot 2022-02-16 at 12 35 18 PM" src="https://user-images.githubusercontent.com/651947/154323853-daa1855b-0c0f-4daa-aae9-74bfa43dbbbc.png">

Could you confirm you are using stretched grid?

**Comment by thng0526** [comment]
Thanks for your response @lizziel. I am using stretched grid with following setting in GCHP.
`CS_RES=48`
`STRETCH_GRID=ON`
`STRETCH_FACTOR=4.0`
`TARGET_LAT=-3.0`
`TARGET_LON=300.0`

Hence, the grid shown in the first plot is what I defined. I knew there are strange things happening with GCPy function compare_single_level but it is fine with single panel as I shown in the first comment. 

Meanwhile, I found the global attributes in GCHP output file include 'target_lat' and 'target_loa' but GCPy can't recognise it. Thus I added 'target_latitude' and 'target_longitude' for GCPy usage.

**Comment by lizziel** [comment]
I think the testing of GCPy with stretched grid output files has not yet been comprehensive. @LiamBindle, do you know what the limitations of GCPy with stretched grid are, if any? For functionalities that are lacking we should make new feature requests in GCPy.

**Comment by LiamBindle** [comment]
Hi @thng0526, thanks for writing.

I have limited experience with GCPy, so bear with me. To respond to a few questions above:

>  May I know if there is any method to generate output in normal lat/lon grid for a stretch grid simulation?

**Option 1:** Configure your simulation to output data on a lat-lon grid
Yes, you can configure your GCHP simulation to output diagnostics on a lat-lon regional grid. The instructions for that are [here](https://gchp.readthedocs.io/en/latest/supplement/config-files/HISTORY.html#defining-grid-labels) (and [here is an example](https://gchp.readthedocs.io/en/latest/supplement/config-files/HISTORY.html#example-history-rc-configuration)). 

**Option 2:** Regrid your stretched-grid data to a lat-lon grid (or any grid)
If you don't want to rerun your simulation, you can regrid your data offline using [sparselt](https://github.com/LiamBindle/sparselt) (to apply regridding weights), ESMF_RegridWeightGen (to generate regridding weights), and [gridspec](https://github.com/LiamBindle/gridspec) (to generate grid definition files for ESMF_RegridWeightGen). This is a robust method, and it's vectorized nicely so it works seamlessly across levels, time slices, and all variables. You can find an example of the workflow [here](https://github.com/LiamBindle/sparselt). Feel free to open an issue on those repos if you need any help. 

**Option 3:** Try to use gcpy.file_regrid to regrid your data
Alternatively, you could use `python -m gcpy.file_regrid` (see help with `-h` option) to regrid your dataset to a lat-lon grid. I don't think this script was intended for regridding like this, but I think it might work.

Note that you can find instructions for plotting stretched-grid and cubed-sphere data in Python [here](https://gchp.readthedocs.io/en/latest/supplement/plotting-output.html#python). The same code works for stretched-grids too.

>  do you know what the limitations of GCPy with stretched grid are, if any?

Unfortunately, I don't. It looks like 60f42c83a0e7c5f00a1b0cad7a3ff5d332ea3149 was when stretched-grid support was first added, but I don't know if it works. It looks like you need to pass an argument called `sg_ref_path` or `sg_dev_path` to `compare_single_level()`, where `sg_*_path` is the path to a NetCDF file that has global attributes `stretch_factor`, `target_longitude`, and `target_latitude`.

@thng0526, After you added the global `stretch_factor`, `target_longitude`, and `target_latitude` attributes to your output file, does your `compare_single_level()` output still look wrong?

**Comment by thng0526** [comment]
Thank you @lizziel @LiamBindle. I think I may make some mistake in HISTORY.rc which leads to the problem. I will change it and run the simulation again. Thanks for the details explanation.
