### ISSUE TITLE
[BUG/ISSUE] Striping when comparing CS output in benchmark plotting

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#147]
## Describe the bug
When comparing different cubed sphere resolution data using the GCPy benchmark plotting routines there appears to be a striping artifact in the difference plots. This occurs when regridding the lower resolution data set to higher resolution cubed sphere. For example, regridding c24 to c48 to compare with c48 data.

## To Reproduce
Run the 1-month benchmark option to plot concentration concentration for GCHP vs GCHP using c48 ref and c24 dev. Here is the ozone surface for 13.3.0-rc.1 (c48) versus 13.4.0-rc.4 (c24).

<img width="999" alt="Screen Shot 2022-04-15 at 10 35 48 AM" src="https://user-images.githubusercontent.com/651947/163585279-03fd70c7-1d87-4082-b34d-12ce43f6134a.png">

## Expected behavior
We would expect no striping in the results (I think).

**Comment by lizziel** [comment]
@sdeastham and @LiamBindle, have you see this pattern when comparing different GCHP resolutions using other software? I think this is a GCPy issue but want to confirm it's not a GCHP data issue.

**Comment by lizziel** [comment]
NOTE: the differences should be reassessed using data produced with the same executable, but at different resolutions. A c48 run of 13.4.0-rc.4 is in progress.

**Comment by sdeastham** [comment]
I think striping is to be expected for sure (imagine how e.g. a gradient in ozone at C48 would show up when compared to the same gradient at C24). I think a good sanity check would be to visually compare the C48 data to the regridded C24 data (i.e. just show the absolute values).

**Comment by lizziel** [comment]
But would the magnitude of striping be so high? In the Southern Ocean, for example, the surface concentrations are generally homogeneous for both ref and dev. I would think that homogeneity would be preserved in the regridding such that the striping would be less pronounced. Although it's hard to tell from the colorbars.
