### ISSUE TITLE
[BUG/ISSUE] Striping in fractional diff plots comparing cubed sphere output

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#15]
When using gcpy function compare_single_level with cubed sphere output there appears to be horizontal striping in the fractional difference plot (lower left subplot). The striping does not appear in any of the other subplots. This seems like it may be an issue with either the calculation of the fractional difference or how python is plotting cubed sphere. The horizontal striping appears to only affect some of the faces, and the boundary between the striping and what looks like correct data is the vertical centerline of a face.

<img width="728" alt="gcpy_cs_fracdiff_striping" src="https://user-images.githubusercontent.com/651947/63122132-00ad9c00-bf74-11e9-9dbe-4ea5f079f39a.png">

**Comment by yantosca** [comment]
I have pushed commit https://github.com/geoschem/gcpy/commit/2b3fd9d9e31443c3dce58ae1a26ef3594660933b, which should now resolve this issue.  (Thanks to Lizzie Lundgren for her contribution in fixing this!)

The fractional difference plots for cubed-sphere no longer show the striping:

![striping_fixed](https://user-images.githubusercontent.com/5880296/63977645-4db86480-ca82-11e9-9e46-a49060925737.png)

Furthermore, we have confirmed that this fix did not introduce any side-effects to the plotting of fractional differences on lon/lat grids:

![striping_fixed_2](https://user-images.githubusercontent.com/5880296/63977676-658fe880-ca82-11e9-84c5-b2542830563e.png)

NOTE: Sometimes you can see some minor striping in the Ref and Dev plots.  These usually were not to the level of striping that we saw in the fractional diff. plots.
