### ISSUE TITLE
[BUG/ISSUE] Update the run_benchmark.py script to import from the gcpy package

### ISSUE THREAD

**Issue by laestrada** [geoschem/gcpy#152]
Currently the run_benchmark.py script imports these two functions like so:
`from modules.run_1yr_fullchem_benchmark import run_benchmark as run_1yr_benchmark`
`from modules.run_1yr_tt_benchmark import run_benchmark as run_1yr_tt_benchmark`

This is problematic because it prevents the script from being copied and run as a standalone script.

**Comment by yantosca** [comment]
The quick fix for this is to add the path to gcpy/benchmark/modules to $PYTHONPATH in your .bashrc file.  We can close this out.
