### ISSUE TITLE
[FEATURE REQUEST]: Allow specification of full path for Benchmark Results

### ISSUE THREAD

**Issue by laestrada** [geoschem/gcpy#153]
## Add your feature request below:
Currently you can specify the name of the folder, but it is always located in the GCC_Dev run directories, allowing to optionally configure the full path would be helpful.

**Comment by yantosca** [comment]
Also I noticed that for the 1-year benchmarks, the output is placed directly into `BenchmarkResults` but not into e.g. `BenchmarkResults/GCC_version_comparison`.  This will lead to overwriting when plotting GCC and GCHP benchmarks.  For now I can manually rename the directory this but it would be good to fix this going forward.
