### ISSUE TITLE
[FEATURE REQUEST] Specify species database path in benchmark yml files

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#162]
Currently the benchmark code assumes the species database is contained in the ref and dev directories at the same level as OutputDir. However, if GEOS-Chem data is archived then the species database is stored elsewhere. In addition, sometimes you may not have the species database with your data but still want to use the benchmark code for comparisons. As is, the GCPy benchmark run will crash if the species database is not found.

I propose solving this problem by specifying the path to the species database in the benchmark yml files. This would provide flexibility and transparency for where the species database is stored, and will avoid the annoying crash if it is not where GCPy assumed it would be relative to the data.

**Comment by yantosca** [comment]
This is now done in commits7f31a44c12edeac525e8db8267a8c17e222d723b and #746569257ca829db7f232c8687ddc865e9ac816f.  This will be implemented with PR #164
