### ISSUE TITLE
[BUG/ISSUE] Inconsistent restart file path usage in 1-year benchmarks

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#163]
There is a discrepancy in the way GCPy 1-year benchmark code uses the restart file directories set in the 1-year benchmark yml files. Some benchmark code, such as the code for mass tables, gets the restart file paths using function `get_filepaths`, which expects the path to the directory in which the `Restarts` folder lives. The returned path has `Restarts` appended to the input directory, along with the filename. In contrast, the Ox budget code expects an input restart file path to include `Restarts` and does not rely on `get_filepaths` to retrieve the restart file path and name.

This is a problem because the restart file path set in the yml file wiill either break the mass table code if `Restarts` is included, or will break the Ox budget code if it is not.

**Comment by yantosca** [comment]
This issue should now be resolved in commit aa062bf7c4ddf264ee9d2c56acba87d240394aa1, which will be applied in PR #164.

**Comment by yantosca** [comment]
We have also removed the 

```yaml
gcc:
  is_pre_14.0: True #or False
```
tags in commit 39050094d51b49ff5d471ec48d799247d136767a.  We now explicitly specify the `outputs_subdir` and `benchmarks_subdir` paths explicitly, and we no longer hardwire the restart file path in the `get_filepath` and `get_filepaths` routines.

**Comment by yantosca** [comment]
NOTE: I still need to fix the restart file paths in `gcpy/budget_ox.py` and `gcpy/budget_tt.py`.  The simplest thing is update them to use `util.get_filepath`.

**Comment by yantosca** [comment]
Restart file paths in budget_ox.py and budget_tt.py are now fixed; we use get_filepath where appropriate.

**Comment by yantosca** [comment]
We can close this issue since PR #164 has been merged into the 1.3.0 development branch.
