### ISSUE TITLE
[FEATURE REQUEST] Update geoschem-gcpy at conda-forge to use older Sphinx versions

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#165]
If you follow the instructions to install geoschem-gcpy (with or without --only-deps) at https://gcpy.readthedocs.io, it will install sphinx 5.11 and sphinx-rtd-theme 1.0.0.  However, other repositories (such as GEOS-Chem Classic) use these package versions for ReadTheDocs, as they have been proven to work together:
```bash
# Requirements for building the GEOS-Chem Classic documentation
#
# NOTE: Use specific versions for Python packages instead of upper
# bounds.  Using an upper bound will not necessarily install the
# intended version if there already is a version that meets the
# criteria present in the Python environment.
#  -- Bob Yantosca and Lizzie Lundgren (22 Jun 2022)
#
# The following package versions have been proven to work together:
#
sphinx==3.5.4
sphinx_rtd_theme==0.5.2
sphinxcontrib-bibtex==2.2.0
recommonmark
docutils==0.16
jinja2==3.0.3
```
We should consider updating the packages in geoschem-gcpy at conda-forge the next time we push an update.

**Comment by yantosca** [comment]
I've updated the `docs/source/environment.yml` file (mostly requesting specific package versions and Python 3.9.6) so this could be used to update the geoschem-gcpy package on conda-forge.

**Comment by msulprizio** [comment]
@yantosca Was this included in the 1.3.0 release or should we change the milestone here?

**Comment by yantosca** [comment]
I believe it was included in 1.3.0

**Comment by yantosca** [comment]
Yes, the current `docs/requirements.txt` is:
```console
# Requirements for building the GCPy documentation
#
# NOTE: Use specific versions for Python packages instead of upper
# bounds.  Using an upper bound will not necessarily install the
# intended version if there already is a version that meets the
# criteria present in the Python environment.
#  -- Bob Yantosca and Lizzie Lundgren (27 Sep 2022)
#
# The following package versions have been proven to work together:
#
sphinx==3.5.4
sphinx_rtd_theme==0.5.2
sphinxcontrib-bibtex==2.2.0
recommonmark
docutils==0.16
jinja2==3.0.3
```console

**Comment by msulprizio** [comment]
Great. I will close out this issue then.
