### ISSUE TITLE
[BUG/ISSUE] Issue with cubed-sphere to cubed-sphere regridding

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#167]
There is currently a problem comparing GCHP output with different grid resolutions using the 1-yr full chemistry benchmark code, as is necessary for 14.0 (C24) which compares to 13.2 (C48). Cubed-sphere to cubed-sphere regridding needs to be tested further in GCPy. Apologies this github issue report does not have more detailed info. This is serving as a reminder for someone on GCST to take a look. The version is GCPy 1.2.0.

**Comment by yantosca** [comment]
Fixed by #253
