### ISSUE TITLE
[QUESTION] How to calculate pressure weighted boundary layer wind speed using GEOS-FP data?

### ISSUE THREAD

**Issue by varisht-tathya** [geoschem/gcpy#170]
## Type your question below:
I wanted to calculate the pressure weighted boundary layer wind speed using GEOS-FP data. I am using " GEOS5 FP 3d time-averaged wind tendencies: tavg3_3d_udt_Nv" to get the eastward and northward wind values and using "tavg1_2d_flx_Nx: 2d time-averaged surface flux diagnostics" to get the boundary layer height. How do I get the wind speed values at the specified height?

I looked up the height and pressure values grid here: http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_vertical_grids#72-layer_vertical_grid but it is for a location at sea level. How do I scale these values for a location at a given altitude? Are the above two products sufficient or is additional data required for the same?

**Comment by lizziel** [comment]
Hi @varisht-tathya, I am closing this issue since it is a science question not specific GCPy or GEOS-Chem.
