### ISSUE TITLE
[QUESTION] How to compute O3 budget for long-term simulation? 

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/gcpy#173]
## Type your question below:
Hello, 
I produced a long-term GCHP (v13.2) simulation from 1997-2017. 
I would like to compute i) the global O3 budget table for my simulation period and ii) the O3 burden for each year like in #113. Is this feature already available for GCHP? 
I would appreciate it if you could help me. 
Thank you in advance.
Maria

**Comment by yantosca** [comment]
Thanks for writing @mtsivlidou.  We do have an Ox budget script in GCPy that we use in benchmarking.  See https://github.com/geoschem/gcpy/blob/main/gcpy/budget_ox.py.  That might do what you want.

**Comment by mtsivlidou** [comment]
Hello, 
Thank you for your answer. I ve seen this example. In the description of the function it is mentioned: 
''Computes the budget of Ox from 1-year GEOS-Chem Classic or GCHP benchmark simulations.''
It was not very clear to me if it can work for simulations longer than 1 year. 
Maria

**Comment by msulprizio** [comment]
Hi @mtsivlidou. The Ox budget script in gcpy works for GCHP, but there was still an issue in computing the GCHP drydep values printed to that table. See https://github.com/geoschem/gcpy/issues/121.
