### ISSUE TITLE
[FEATURE REQUEST] Add switch to quickly disable parallelization in gcpy

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#179]
Currently, to disable parallelization, one has to manually go into the code and change `Parallel(n_jobs=-1)` to `Parallel(n_jobs=1)` where applicable. To simplify debugging, we should add a switch to the config file to easily disable parallelization throughout.

**Comment by yantosca** [comment]
Actually if `n_job=1`, that turns off the parallelization.

**Comment by lizziel** [comment]
In the past I have found that using n_job=1 did not completely disable it. I had to comment out the parallelization to better debug problems. Maybe things are different now?

**Comment by yantosca** [comment]
We can now close this as PR #246 has been merged into the GCPy 1.4.0 development stream.
