### ISSUE TITLE
how to use grid argument in gcpy.plot.single_panel()?

### ISSUE THREAD

**Issue by Gracedyg** [geoschem/gcpy#183]
I'm using gcpy.plot.single_panel() to produce a concentration image map from a .nc file created by GEOS-Chem. I am wondering how to add ticks of latitude and longitude information to the image map. If using the grid argument is helpful, can anyone teach me how to use it? an example may be helpful.
```python
def single_panel(plot_vals, ax=None, plot_type="single_level",
    **grid={},** gridtype="", title="fill",comap=WhGrYlRd,
    norm=[],unit="",extent=(None, None, None, None),
    masked_data=None,use_cmap_RdBu=False,
    log_color_scale=False, add_cb=True,
    pres_range=[0, 2000], pedge=np.full((1, 1), -1),
    pedge_ind=np.full((1,1), -1), log_yaxis=False,
    xtick_positions=[], xticklabels=[], proj=ccrs.PlateCarree(),
    sg_path='', ll_plot_func="imshow", vert_params=[[],[]],
    pdfname="", return_list_of_plots=False **extra_plot_args
):
```

**Comment by lizziel** [comment]
Hi @Gracedyg. The GEOS-Chem Support Team does not provide this level of python support. The best way to figure out how to make this change is to read through the python code in GCPy and play around with it, also looking at python documentation online for adding to ticks to maps.
