### ISSUE TITLE
[BUG/ISSUE] Regrid(filename) requires PIO and does not work if ESMF has not been built with MPI support

### ISSUE THREAD

**Issue by SadiaToma** [geoschem/gcpy#184]
## Type your question below:
Hi,

I have been trying to use the gcpy.file_regrid to create a new restart file. In past, using the same version of gcpy I was able to run gcpy.plot.single_panel commands. I am getting the following error:
```console
/home/safrin/gcpy/gcpy/file_regrid.py:8: DeprecationWarning: distutils Version classes are deprecated. Use packaging.ver  sion instead.
  if LooseVersion(xe.__version__) < LooseVersion("0.2.1"):
Create weight file: ./conservative_sg01f0b92_F0_sgd82495f_F0.nc
Traceback (most recent call last):
  File "/home/safrin/.conda/envs/gcpy_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/safrin/.conda/envs/gcpy_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/safrin/gcpy/gcpy/file_regrid.py", line 420, in <module>
    file_regrid(
  File "/home/safrin/gcpy/gcpy/file_regrid.py", line 106, in file_regrid
    regridders = make_regridder_S2S(
  File "/home/safrin/gcpy/gcpy/regrid.py", line 229, in make_regridder_S2S
    regridder = xe.Regridder(igrid_list[i_face],
  File "/home/safrin/.conda/envs/gcpy_env/lib/python3.9/site-packages/xesmf/frontend.py", line 235, in __init__
    self._write_weight_file()
  File "/home/safrin/.conda/envs/gcpy_env/lib/python3.9/site-packages/xesmf/frontend.py", line 277, in _write_weight_fil  e
    regrid = esmf_regrid_build(self._grid_in, self._grid_out, self.method,
  File "/home/safrin/.conda/envs/gcpy_env/lib/python3.9/site-packages/xesmf/backend.py", line 277, in esmf_regrid_build
    regrid = ESMF.Regrid(sourcefield, destfield, filename=filename,
  File "/home/safrin/.conda/envs/gcpy_env/lib/python3.9/site-packages/ESMF/util/decorators.py", line 81, in new_func
    return func(*args, **kwargs)
  File "/home/safrin/.conda/envs/gcpy_env/lib/python3.9/site-packages/ESMF/api/regrid.py", line 149, in __init__
    raise ImportError(msg)
ImportError: Regrid(filename) requires PIO and does not work if ESMF has not been built with MPI support
```
I had the feeling that something going wrong with the versions of Python and the gcpy I am using. However, I didn't find that a logical solution to try installing gcpy with a older version of python. Hence didn't try to do that. So, I would appreciate if anyone can suggest  a possible fix for this problem. Thanks.

**Comment by yantosca** [comment]
Thanks for writing @SadiaToma.  Are you working locally on a PC?  If so that might be the issue.  ESMPy will not install on PC architectures (only Linux or MacOS) because ESMF is restricted to those architectures.

You can also try to create a new Python environment for GCPy using this environment file: 
https://github.com/geoschem/gcpy/blob/main/docs/environment_files/environment.yml

and then type at the prompt:
```console
conda env create --name gcpy_env --file=environment.yml
```
We have restricted the Python environment to Python 3.9.6 and specific package versions as listed in the `environment.yml` file.  This is to minimize the chance that package updates will render some feature of GCPy inoperable.

**Comment by yantosca** [comment]
@SadiaToma: you can also download the GCPy version 1.3.2 from conda-forge and that is equivalent to building from the environment file above:
```console
$ conda config --add channels conda-forge
$ conda install geoschem-gcpy==1.3.2
```
Also tagging @Jourdan-He and @SaptSinha for reference purposes.

**Comment by SadiaToma** [comment]
Hi @yantosca,

Thank you so much for your reply. I did try installing gcpy in both ways. However, now I am getting another set of warnings and is being killed before the creation of regrid file.
`/home/safrin/miniconda3/envs/gcpy_env_dec33/lib/python3.9/site-packages/xesmf/frontend.py:473: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset.
using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset.
Killed
`

Do you have any other suggestions for me to try?  Thanks.

**Comment by SadiaToma** [comment]
Hi @yantosca,

Thank you so much for your reply. I did try installing gcpy in both ways. However, now I am getting another set of warnings and is being killed before the creation of regrid file.
/home/safrin/miniconda3/envs/gcpy_env_dec33/lib/python3.9/site-packages/xesmf/frontend.py:473: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version. ds_out = xr.apply_ufunc( using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset. using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset. using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset. using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset. using dimensions ('Y', 'X') from data variable SPC_RCOOH as the horizontal dimensions for this dataset. Killed 

Do you have any other suggestions for me to try? Thanks.
