### ISSUE TITLE
[BUG/ISSUE] Filp vertical dimention for the calculation of GCHP transport tracer budget in gcpy?

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/gcpy#185]
### What institution are you from?
Washington University in St. Louis
### Description of the problem
I just noticed a small bug in the calculation of GCHP transport tracer budget table in https://github.com/geoschem/gcpy/blob/main/gcpy/budget_tt.py
It looks like the emissions diagnostics in GCHP transport tracer should be flipped (surface layer at 72nd layer), which is not reflected in the calculation of the budget table. 

It will only affect the source flux in the table. As a result, the source in GCC for Be7 is around [0.11 g/d](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/13.2.0-beta.2/GCClassic/TransportTracers-LuoWetdep/BenchmarkResults/Tables/Pb-Be_budget_troposphere.txt), while that in GCHP is only [0.045 g/d](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/13.2.0-beta.2/GCHP/TransportTracers-LuoWetdep/BenchmarkResults/GCHP_version_comparison/Tables/Pb-Be_budget_troposphere.txt) . 

I tested flipping the vertical dimension can get the source flux comparable with GCC, so hopefully it is the reason.

**Comment by msulprizio** [comment]
Thanks for reporting this @1Dandan. I have transferred the issue to the gcpy repository since it is an issue with the code there. We will try to address this soon.

**Comment by lizziel** [comment]
I put a fix in for this in https://github.com/geoschem/gcpy/pull/192. @1Dandan, could you look at those changes and verify they are correspond to your fix?

**Comment by lizziel** [comment]
This update has been merged.
