### ISSUE TITLE
[BUG/ISSUE] Using GCPy file_regrid on GCHP restart file produces several output files

### ISSUE THREAD

**Issue by Twize** [geoschem/gcpy#193]
Hi, I am currently trying to configure a GCHP stretch-grid simulation, and want to re-grid one of the standard GCHP restart files to match the stretch-grid parameters in my simulation following the instructions here: https://gchp.readthedocs.io/en/13.0.1/stretched-grid.html. When I run the following command: 

`python -m gcpy.file_regrid -i initial_GEOSChem_rst.c90_fullchem.nc  --dim_format_in checkpoint -o sg_restart_c48_3_254_66.nc --cs_res_out 48 --sg_params_out 3.0 254.0 66.0 --dim_format_out checkpoint`

I expected it to produce a single resulting re-gridded restart file. However, it produces multiple output .nc files labeled sg_restart_c48_3_254_66.nc0, sg_restart_c48_3_254_66.nc1, etc (6 in total, the same as the number of cube faces). Is this the expected behaviour? 

I am using gcpy version 1.3.2 which I installed using: 
`conda config --add channels conda-forge`
`conda install geoschem-gcpy==1.3.2`

**Comment by lizziel** [comment]
Tagging @Jourdan-He and @kilicomu on this who may be best able to help you. There is a currently PR open in this repository to fix regridding.

**Comment by kilicomu** [comment]
Hi @Twize - I have seen this issue, I just haven't been able to make time to get back to you yet. I'll do so tomorrow. Hope that's ok!

**Comment by Twize** [comment]
> Hi @Twize - I have seen this issue, I just haven't been able to make time to get back to you yet. I'll do so tomorrow. Hope that's ok!

No problem at all, whenever you get around to it!

**Comment by kilicomu** [comment]
@Twize Sorry - in the time between yesterday's message and now I've found another problem with the stretched grid that's likely to cause problems with runs.

I'll try and work through that asap then get back to you here about regridding.

**Comment by Twize** [comment]
@kilicomu no rush! I've paused my GCHP work temporarily while I wait for the release of v14.1.1 so that I can use GFAS biomass burning emissions in my simulations.

**Comment by kilicomu** [comment]
Hey @Twize - just to let you know that the next release of GCPy (coming soon!) will have some new documentation and a submodule that will allow you to correctly regrid GCHP restart files.

Sorry it's taken a while to get back to you on this. Once that's out please let me know if you're able to get on and do what you need to do.

**Comment by Twize** [comment]
Hi @kilicomu, thanks for the update! Will do.
