### ISSUE TITLE
Creating a .txt file using GCPy

### ISSUE THREAD

**Issue by TylerElgiar** [geoschem/gcpy#195]
## Type your question below:

I am curious if there is a way to create a .txt file containing mass concentrations of certain species using GCPy. I see on the "read the docs" site that there is a way to create a time series, but I am unable to find where I can only extract a .txt file to later use in excel.

**Comment by yantosca** [comment]
Thanks for writing @TylerElgiar.  You might not need GCPy to do this but could try another data structure like Pandas dataframe.  I think there might also be a csv package in Python but you'll have to look that up.

**Comment by TylerElgiar** [comment]
Okay, thanks for the quick response. I'll try one of these other ways. I just wanted to make sure there wasn't a quick and easy way to do this in GCPy, before going down another road.

Thanks,
Tyler
     On Tuesday, January 24, 2023, 10:08:10 AM MST, Bob Yantosca ***@***.***> wrote:  
 
 


Thanks for writing @TylerElgiar. You might not need GCPy to do this but could try another data structure like Pandas dataframe. I think there might also be a csv package in Python but you'll have to look that up.

**Comment by yantosca** [comment]
No problem @TylerElgiar.  GCPy hasn't tried to duplicate other existing Python functionality where it exists.  It's mostly used for GEOS-Chem benchmarking, with some user-facing plotting and utility codes.  

I'll close out this issue now.  Thanks!
