### ISSUE TITLE
[QUESTION] ESMF module not found error

### ISSUE THREAD

**Issue by liwenjia12** [geoschem/gcpy#196]
## Type your question below:
I don't know what's wrong with it.
(gcpy_demo) liwenjia@liwenjia-KLVF-XX:~/Desktop$ python                                                                  
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03)                                                  
[GCC 10.4.0] on linux                                                                                                    
Type "help", "copyright", "credits" or "license" for more information.                                                   
>>> import gcpy
Traceback (most recent call last):                                                                                       
  File "<stdin>", line 1, in <module>                                                                                    
  File "/home/liwenjia/miniconda3/envs/gcpy_demo/lib/python3.9/site-packages/gcpy/__init__.py", line 19, in <module>     
    from .regrid import *                                                                                                
  File "/home/liwenjia/miniconda3/envs/gcpy_demo/lib/python3.9/site-packages/gcpy/regrid.py", line 4, in <module>        
    import xesmf as xe                                                                                                   
  File "/home/liwenjia/miniconda3/envs/gcpy_demo/lib/python3.9/site-packages/xesmf/__init__.py", line 4, in <module>     
    from . frontend import Regridder                                                                                     
  File "/home/liwenjia/miniconda3/envs/gcpy_demo/lib/python3.9/site-packages/xesmf/frontend.py", line 10, in <module>    
    from . backend import (esmf_grid, esmf_locstream, add_corner,                                                        
  File "/home/liwenjia/miniconda3/envs/gcpy_demo/lib/python3.9/site-packages/xesmf/backend.py", line 19, in <module>     
    import ESMF                                                                                                          
ModuleNotFoundError: No module named 'ESMF'                                                                              
>>>

**Comment by lizziel** [comment]
Hi @liwenjia12, have you tried setting up GCPy using the ReadTheDocs instructions here? https://gcpy.readthedocs.io/en/stable/Getting-Started-with-GCPy.html

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by hmhorow** [comment]
Hannah Horowitz from UIUC here. My group and I had a similar issue. We were able to get it to work - once we downloaded the environment file from here:
https://github.com/geoschem/gcpy/blob/main/docs/environment_files/environment.yml 
put it on our server and then followed the instructions on the read the doc page linked above. 
It was not clear to me from the way the instructions were written that that was necessary. Not sure if there is another way to get the environment file. The way this is written: 
```
# Navigate to the top-level GCPy folder
cd /path/to/gcpy
```
makes it sound like you first would use github to first download gcpy.. before installing it? But I think only the environment file is truly necessary. 

One potential thing that I have seen with ESMF/xesmf more generally in the past, is that you need to deactivate and reactivate the environment for the ESMF package to work. Perhaps could be an explanation as well. I did a lot of deactivating and activating so I am not sure if it was necessary or not.

**Comment by lizziel** [comment]
Thanks Hannah for the feedback. I need to set up an environment for GCPy on a new computer so I'll follow the docs and update as needed for clarity.

**Comment by hmhorow** [comment]
Thanks Lizzie! Also note that I am new to using environment.yml files to manage conda environments, so my perspective is from a novice in that respect!

**Comment by liwenjia12** [comment]
Thanks for your advice, I have had finished this question with your help, I really appreciate it!!!
