### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by TylerElgiar** [geoschem/gcpy#203]
## Type your question below:
I am making zonal mean plots for a Hg simulation. I am curious if I am able to specify the extent (lat and lon) for the plot similar to the single level plots. I would like to create a zonal mean plot over a specific location instead of the entire globe if possible.

**Comment by lizziel** [comment]
Hi @TylerElgiar. I don't think this is a currently an option but you can add it in to your clone of GCPy. The plotting code is basic python using cartopy and matplotlib.

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!
