### ISSUE TITLE
[FEATURE REQUEST] Include species delta mass from restart files in full column budget tables

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#214]
GCPy has the capability to produce budget tables but does not currently use it during benchmarking. This means that budget diagnostics do not regularly get looked at. A quick and easy way to validate them is to include the change in mass per species as computed from restart files within the full column budgets, under the accumulation as computed from the budget diagnostics. We would expect them to be very close in value. If they are not then there is an indication the budget diagnostics might not be working as they should.

**Comment by lizziel** [comment]
I started this work. I think rather than include the change in mass from restart files within the operations budget table I will make a new table for mass accumulation. Ref will be ref restart mass at end of simulation minus at start of simulation, and Dev will be the same (dev restart mass at end of simulation minus at start of simulation). These values can be cross-reference with operations budget table or looked at on their own as another optional benchmarking tool.

**Comment by lizziel** [comment]
See https://github.com/geoschem/gcpy/pull/216

**Comment by yantosca** [comment]
This has now been merged into the GCPy 1.4.0 development stream.  We can close this issue out.
