### ISSUE TITLE
[QUESTION] Creating difference maps for total HgII

### ISSUE THREAD

**Issue by TylerElgiar** [geoschem/gcpy#215]
## Type your question below:

Name: Tyler Elgiar
Institution: Utah State University

Hello,

I have been trying to create difference maps using output from two different GEOS-Chem Hg simulations for total HgII. Originally I was trying to sum up all HgII species into one plot using the six panel comparison plotting function in GCPy. I have not been able to do this successfully. I looked into some benchmark scripts provided by @arifein, the "Hg2Plot.py" script in particular. However when I try to install the "diff_plots_Hg" module I receive the following errors:

ERROR: Could not find a version that satisfies the requirement diff_plots_Hg (from versions: none)
ERROR: No matching distribution found for diff_plots_Hg

I imagine it's a simple fix, however, I'm not quite sure where to retrieve this module to be able to run the script.
Is this the best way to generate the diff maps for total HgII? Or is there another way that may be better?
Any information is greatly appreciated.

Thanks!

**Comment by arifein** [comment]
Hi Tyler, I usually run the benchmark scripts by downloading the whole repository: https://github.com/arifein/pythonHgBenchmark. Then I run the main.py file to produce the relevant plots. The diff_plots_Hg module is a script (diff_plots_Hg.py) within the repository, which contains the relevant functions for producing the comparison plots. And this is then loaded in the Hg2Plot.py script with the command `from diff_plots_Hg import diff_plots
`. Maybe it would help clarify if you expand a bit step-by-step what you are doing, and where the error you mention comes up? I don't fully understand what you mean by "install" here

**Comment by TylerElgiar** [comment]
Thanks for your reply. That makes more sense now. I was trying to use "pip install" to retrieve the diff_plots_Hg module, this is where the error occurred. I will try this again by downloading the whole repository and following the steps you've mentioned.

**Comment by yantosca** [comment]
I will close out this issue as it is related to the external Hg benchmarking code.

@arifein: We should probably try to merge what you have with GCPy at some point.
