### ISSUE TITLE
[Feature Request] Reduce length and remove space from budget operations table name

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#218]
Name: Lizzie Lundgren
Institution: Harvard University

The operations budget table name is very long and contains a space. For example:
`Budgets_After_Operations_2019-07-01T00:00:00 - 2019-07-01T01:00:00.txt`

The table could instead be named simply `Budgets_After_Operations.txt`, dropping the time interval strings.  It is possible the time strings are needed if generating the budget from the 1-year benchmark but I am not sure. If it is, then we can come up with a more concise time string to append to the filename.

This is not urgent but something to address at some point.

**Comment by yantosca** [comment]
In the 1-year benchmark scripts it looks like we already have short filenames passed via `label`:
```python
               # Create tables
                bmk.make_benchmark_mass_tables(
                    refpath,
                    gchp_vs_gcc_refstr,
                    devpath,
                    gchp_vs_gcc_devstr,
                    dst=gchp_vs_gcc_tablesdir,
                    subdst=bmk_mon_yr_strs_dev[m],
                    label=f"at 01{bmk_mon_yr_strs_dev[m]}",
                    overwrite=True,
                    spcdb_dir=spcdb_dir,
                    dev_met_extra=devareapath
```

**Comment by yantosca** [comment]
PR #227 has now been merged, so we can close this issue.
