### ISSUE TITLE
Difficulty converting .bpch to netcdf format using GCPy library

### ISSUE THREAD

**Issue by gouravsaha1995** [geoschem/gcpy#219]
I am stuck with the conversion of a .bpch file from the GEOS-Chem output to the netcdf format using the GCPy library. These are the common errors I am being shown. I have followed the exact steps for installing GCPy alongwith the list of dependencies:

1. AttributeError: module 'gcpy' has no attribute 'open_bpchdataset'

>>> import gcpy
>>> import xarray as xr
>>> bpch_file = 'path/to/your/file.bpch'
>>> bpch_file = '/home/cas/irdstaff/ird600165/scratch/gourav/post_processing_tools/ctm.bpch'
>>> bpch_data = gcpy.open_bpchdataset(bpch_file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gcpy' has no attribute 'open_bpchdataset'
>>> from gcpy import bpch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'bpch' from 'gcpy' (/home/cas/irdstaff/ird600165/.conda/envs/gcpy_env/lib/python3.9/site-packages/geoschem_gcpy-1.3.2-py3.9.egg/gcpy/__init__.py)
>>> data = gcpy.open_bpchdataset(bpch_file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gcpy' has no attribute 'open_bpchdataset'
>>>

This is how my python code looks like.

**Comment by yantosca** [comment]
Thanks for writing @gouravsaha1995.  I think you need to use `xbpch.open_bpchdataset` instead of `gcpy.open_bpchdataset`.   See the example program: https://gcpy.readthedocs.io/en/stable/bpch_to_nc.html

In older versions of GCPy, I think we had a wrapper script `gcpy.open_bpchdataset` but that has been removed in the newer versions.

**Comment by yantosca** [comment]
Also note @gouravsaha1995, the xbpch library is technically no longer supported as its (1) developer has left the GEOS-Chem community and (2) we have migrated to netCDF diagnostics.  I think you may need to use xarray==0.11 in order to use xbpch, as subsequent package updates have broken it.

**Comment by gouravsaha1995** [comment]
@yantosca Hello Sir!

Hence, I tried running the sample conversion script given in the website to convert .bpch to .nc format and there too this error is being shown:
$ ./code.py
Traceback (most recent call last):
  File "/home/cas/irdstaff/ird600165/.conda/envs/cas_env/lib/python3.10/site-packages/xarray/core/common.py", line 300, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: 'Dataset' object has no attribute '_file_obj'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/cas/irdstaff/ird600165/gourav/post_processing_tools/./code.py", line 43, in <module>
    ds = xb.open_bpchdataset(filename=bpchfile,
  File "/home/cas/irdstaff/ird600165/.conda/envs/cas_env/lib/python3.10/site-packages/xbpch/core.py", line 86, in open_bpchdataset
    ds._file_obj = store._bpch
  File "/home/cas/irdstaff/ird600165/.conda/envs/cas_env/lib/python3.10/site-packages/xarray/core/common.py", line 308, in __setattr__
    raise AttributeError(
AttributeError: cannot set attribute '_file_obj' on a 'Dataset' object. Use __setitem__ styleassignment (e.g., `ds['name'] = ...`) instead of assigning variables.

Sir. would you please kindly tell me where am I going wrong and what do I need to do to be able to successfully convert a .bpch dataset to a .nc dataset using the required libraries?

**Comment by yantosca** [comment]
Thanks for writing @gouravsaha1995.  A couple of things:

1. Python 3.10 may be too "new" for xbpch.  Try using an older python like 3.7.
2. Xbpch requires a very old version of xarray (I think 0.11).  If you are using a newer version you'll need to downgrade.

**Comment by yantosca** [comment]
Closing out this issue now.
