### ISSUE TITLE
[FEATURE REQUEST] Global mass table

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#22]
The GCSC has requested global mass tables for all species as part of the benchmark output. These values can be computed from the restart file output at the end of the simulation.

**Comment by msulprizio** [comment]
Initial modifications have been pushed to the [feature/global_mass_table](https://github.com/geoschem/gcpy/commits/feature/global_mass_table) branch. Global totals for the entire atmosphere can now be written out for all advected species. @yantosca is working on getting this to work for the troposphere only.

Example output:
```
###############################################################################
### Global mass at end of simulation (Trop + Strat)                         ###
### Ref = GC_12.4.0; Dev = GC_12.5.0                                        ###
###############################################################################
                              Ref                 Dev      Dev - Ref
ACET         :       12969.661133        13947.962891     978.301758 Gg
ACTA         :         283.086761          326.426453      43.339691 Gg
AERI         :           4.424655            4.414498      -0.010158 Gg
ALD2         :         632.746094          772.405273     139.659180 Gg
ALK4         :        1597.031738         1701.354004     104.322266 Gg
...
```

**Comment by yantosca** [comment]
I have completed the modifications that will generate both global and tropospheric sums of species mass.  These are in commits: https://github.com/geoschem/gcpy/commit/6038a5b9481cf4610382c60f6b2d5449207c690d, https://github.com/geoschem/gcpy/commit/fcb43e805d063c712e81efc9d90d3fda443e19e4, https://github.com/geoschem/gcpy/commit/013918cfe539dfa2c9ef655b21e58acbd93a334e, https://github.com/geoschem/gcpy/commit/99885fee1a5e8cb1fba7bdd07553d58e3ec774ee, https://github.com/geoschem/gcpy/commit/6675143e24513f7800752dd149cc23961abe5075, https://github.com/geoschem/gcpy/commit/0a727b1263b3b9682dc734974aa77bbe5d5dcd9b, https://github.com/geoschem/gcpy/commit/930674632f2f8471baba40abe17a39b9002c9fa3, and https://github.com/geoschem/gcpy/commit/b98e2735a221c740576aebeeac2b3e74100cb02a.

The corresponding tropopsheric-only species mass totals look like:

    ##############################################################################    #
    ### Global mass at end of simulation (Trop only)                            ###
    ### Ref = GC_12.4.0; Dev = GC_12.5.0                                        ###
    ############################################################################## #
                                           Ref                 Dev      Dev - Ref
    ACET                  :         435.055450          450.541809      15.486359 Gg
    ACTA                  :           2.498169            2.702352       0.204183 Gg
    AERI                  :           1.247040            1.247155       0.000115 Gg
    ALD2                  :           2.222366            2.361204       0.138838 Gg
    ALK4                  :          12.862467           13.234366       0.371900 Gg

etc..

**Comment by yantosca** [comment]
We are currently investigating an issue where the trop-only totals look too low.

**Comment by yantosca** [comment]
It turns out the masking logic we had implemented was producing the opposite of the desired result.  Commit https://github.com/geoschem/gcpy/commit/e72a998b79ad14f60238bed186fa8a5189f9d398 now fixes this issue.  We now obtain tropospheric masses like these:

    ###############################################################################
    ### Global mass at end of simulation (Trop only)                            ###
    ### Ref = GC_12.4.0; Dev = GC_12.5.0                                        ###
    ###############################################################################
                                           Ref                 Dev      Dev - Ref
    ACET                  :       12534.605469        13497.419922     962.814453 Gg
    ACTA                  :         280.588562          323.724030      43.135468 Gg
    AERI                  :           3.177616            3.167343      -0.010273 Gg
    ALD2                  :         630.523743          770.044128     139.520386 Gg
    ALK4                  :        1584.169312         1688.119873     103.950562 Gg

**Comment by lizziel** [comment]
Global mass table generation is not yet possible with GCHP because instantaneous meteorology fields are not available in the restart file. These fields will be added in 12.7 at which time global mass tables will be able to be created for GCHP benchmarks. This issue should stay opened until that time.

**Comment by msulprizio** [comment]
Daniel Jacob requested non-advected species be added to the global mass tables. In order to achieve this, we need to define molecular weights for those species. I will work with Kelvin Bates on this task.

**Comment by yantosca** [comment]
We probably should add the MW's into the species DB in GEOS-Chem -- then we can write out the JSON file that is used by GCPy from there.

**Comment by yantosca** [comment]
Note that there is a separate issue for GCHP vs. GCC mass tables (https://github.com/geoschem/gcpy/issues/67)

**Comment by yantosca** [comment]
Also an issue that still needs to be resolved: https://github.com/geoschem/gcpy/issues/4

I will close out this issue as the global mass tables are now part of the benchmark (at least for GCC vs. GCC).
