### ISSUE TITLE
[FEATURE REQUEST] Remove test data option from benchmarking code

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#220]
The test data option in GCPy benchmarking was a work-around for when the full chemistry benchmarking was hard-coded for duration, year, etc. Now that the benchmarking configuration file is very flexible with regards to these parameters we do not need to have stored test data. Removing the option also means we will not need to maintain up-to-date test data that is usually a duplicate of data from a previous benchmark run.

**Comment by yantosca** [comment]
@lizziel: Can we also remove the GCHP switches `is_pre_13.1` and `is_pre_14.0`?   Chances are we will not be going back to those versions soon.

**Comment by yantosca** [comment]
Also we would need to make the corresponding changes to the `1hr_benchmark.yml` and `1mo_benchmark.yml` files in the https://github.com/geoschem/gc-cloud-infrastructure repo as well.

**Comment by lizziel** [comment]
> Can we also remove the GCHP switches is_pre_13.1 and is_pre_14.0? Chances are we will not be going back to those versions soon.

I think we can remove is_pre_13.1, but not is_pre_14.0. I have been comparing to 13.3 (before the pressure bug came in) and having that option has been useful. I suggest we remove it when we move to 15.0.

> Also we would need to make the corresponding changes to the 1hr_benchmark.yml and 1mo_benchmark.yml files in the https://github.com/geoschem/gc-cloud-infrastructure repo as well.

I haven't looked at those so am not sure. If they have the test data option then yes. Hopefully at some point we can stop having those duplicated in that repo. It would be better to have them in gcpy and have gcpy as a submodule that repo if they are needed there.

**Comment by yantosca** [comment]
@lizziel: We can now close out this issue as PR #222 has been merged.
