### ISSUE TITLE
[FEATURE REQUEST] Add tool for quickly obtaining I,J indices when given lat,lon values

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#244]
We previously had a function (CTM_INDEX in GAMAP, I believe) that would return the I,J indices of a grid box when provided with the lat,lon coordinates. It would be useful to have a quick tool to do something like this in gcpy.

**Comment by yantosca** [comment]
Thanks @msulprizio.  We now have this capability in the model vs. obs plots.  We can try abstracting that out into a separate function.

**Comment by yantosca** [comment]
@msulprizio: I have been developing this capability in the `feature/update-model-vs-obs` branch.  This can go into the next GCPy version as time allows for development.

**Comment by yantosca** [comment]
This will be fixed by PR #277

**Comment by yantosca** [comment]
We can close this issue as PR #277 has been merged into dev.
