### ISSUE TITLE
[BUG/ISSUE] Issue with colorbars and axis labels in latest benchmark plots

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#259]
## Describe the bug

The latest 1-month benchmarks run by the cloud produce plots with colorbars and axis labels that overlap with other figures or other values. See the examples below:

<img width="461" alt="Screenshot 2023-09-14 at 3 00 23 PM" src="https://github.com/geoschem/gcpy/assets/4805437/c886c917-bc01-4b28-a4f2-cc8b2a0dad65">

<img width="466" alt="Screenshot 2023-09-14 at 2 59 57 PM" src="https://github.com/geoschem/gcpy/assets/4805437/6c47c7b8-12f2-4a77-900a-f6ddaa17befa">

**Comment by yantosca** [comment]
I'll take a look @msulprizio.  Wonder if it's a library issue or something.  We now use matplotlib 3.7.2, maybe they changed the default size or something.

**Comment by yantosca** [comment]
Fixed by #260

**Comment by yantosca** [comment]
We can close this issue as #260 has been merged into the GCPy 1.4.0 development stream.
