### ISSUE TITLE
[FEATURE REQUEST] Add dry deposition velocities to benchmark output

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#273]
Mat Evans has requested we include annual mean dry deposition velocity output for key species (e.g. O3, NH4, HNO3, Acetone, SO4, NIT, NH4) in the 1-month and 1-year benchmark output to track changes to the dry deposition. These output are already saved out in the benchmark simulations. We will need to update gcpy to either plot or tabulate the data and compare to the previous version.

**Comment by yantosca** [comment]
I can try to implement this.  It may be a little time before I can get to it.

**Comment by yantosca** [comment]
Also see related issue https://github.com/geoschem/geos-chem/issues/2065

**Comment by yantosca** [comment]
We can close this issue now, as PR #280 has been merged.
