### ISSUE TITLE
[FEATURE REQUEST] Abstract plotting data onto a map or zonal mean into a routine that can be reused

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#30]
In routines compute_single_level and compute_zonal_mean, we end up repeating much of the same code to create a single-level map or zonal-mean plot.  As time allows, we should try to abstract this plotting code into routines that can be repeatedly called.  This would also facilitate development of general-purpose plotting routines for users.

**Comment by yantosca** [comment]
Akua might be able to help us identify how to abstract repeated code into functions in GCPy.

**Comment by WilliamDowns** [comment]
Compute_single_level and compute_zonal_mean have had much of their repetitive code abstracted into shared routines, including benchmark.sixplot (which itself uses core.gcplot) for creating the 6-panel benchmark plots, and regrid.create_regridders for making appropriate grids and regridders.
