### ISSUE TITLE
[FEATURE REQUEST] Defining the scope & use cases of GCPy in README

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gcpy#38]
## Motivation 
In README or somewhere there should be a list/table of what GCPy is intended to do (as well as NOT indented to do). One apparent question a new user will have is "in what cases should I download & learn GCPy?". Having a clear answer to that will bring many benefits:

1. By narrowing down the scope of GCPy, we can out-source many common tasks to the upstream xarray/numpy/scipy. This avoids reinventing the wheel and reduces development burden. 
2. We can worry less about GCPy's API stability and backward compatibility. A major issue for new packages like GCPy is that the APIs can change frequently from version to version (often for good reasons like better efficiency or more functionalities). On the other hand, upstream packages have much more stable APIs. By having a small number of APIs, users will feel less disturbed by version updates.
3. Some general-purpose functionalities can be [pushed upstream to xarray](http://xarray.pydata.org/en/stable/contributing.html) so they can sustain longer and benefit a broader community. There are a lot of model-specific packages (for example NCAR's esmlab https://github.com/NCAR/esmlab), but I feel that many functionalities are duplicating. For example, the code handling cubed-sphere might be easily adapted for other multi-tile grids -- this is a very common need in Earth science models (e.g. [xgcm also has a notion of multi-tile grid](https://xgcm.readthedocs.io/en/latest/grid_topology.html))

## Examples

Some apparent GCPy use cases:
1. Generate the standard benchmark plots
2. Obtain GEOS-Chem's horizontal/vertical grid information
3. GCHP-specific regridding functionalities

Some apparent non-GCPy use cases:
1. Modify a NetCDF file (crop a domain, extract some variables)
2. Simple 2D plotting on lat-lon grid, or 1D plotting against time
3. All statistical analysis tools (should be done in SciPy/sklearn)

**Comment by yantosca** [comment]
I have now pushed commit https://github.com/geoschem/gcpy/commit/2d9e8bc958c1ad7c7ac35a2575935ff56a5ba971 which adds some text to the README file that explains what GCPy is meant to do and what it isn't.  Let me know if this looks OK.  If so we can move to close out the issue.

**Comment by JiaweiZhuang** [comment]
Thanks @yantosca ! Looks good to me. Eventually each item should have a link to example code.

**Comment by yantosca** [comment]
We can add the example codes later.  For the time being I will close out this issue.
