### ISSUE TITLE
Trouble setting up gcpy on Mac

### ISSUE THREAD

**Issue by Jun-Meng** [geoschem/gcpy#4]
Hi everyone, 
I'm trying to setup gcpy on my Mac. I have anaconda3 installed. I downloaded gcpy from git and put it under my Desktop. I used this command to create the environment: 
conda env create -vv -n gcpy gcpy/docs/environment.yml. 
However, I got the error below: 
<img width="959" alt="Screen Shot 2019-05-16 at 4 21 19 PM" src="https://user-images.githubusercontent.com/22326325/57882571-64e88480-77fa-11e9-89fe-544838aa4cb5.png">
I was wondering if this is the right way to set up gcpy? 
Does anybody have similar issues? 

Jun Meng

**Comment by lizziel** [comment]
Hi Jun,
Try using this command instead:
conda env create -f environment.yml

The name of the virtual env will match whatever is in the yml file, in this case gcpy.

**Comment by Jun-Meng** [comment]
Thanks Lizzie! It works now. I use "conda env create gcpy/docs/environment.yml"

**Comment by Jun-Meng** [comment]
Hi all, 

I set up the gcpy environment. The xarray and xbpch in my gcpy environment are 0.11.3 and 0.3.4.  I run jupyter notebook using my gcpy environment. However, I still run into the first problem Prof. Prasad had, as follows: 

_ #---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-f8d96000f106> in <module>
      2 import numpy as np
      3 import xarray as xr
----> 4 import xbpch
      5 import gcpy
      6 

~/anaconda3/envs/gcpy/lib/python3.6/site-packages/xbpch/__init__.py in <module>
      5     pass
      6 
----> 7 from . bpch import BPCHFile
      8 from . core import open_bpchdataset, open_mfbpchdataset

~/anaconda3/envs/gcpy/lib/python3.6/site-packages/xbpch/bpch.py in <module>
      9 import os
     10 
---> 11 from xarray.core.pycompat import OrderedDict
     12 
     13 from . uff import FortranFile

ImportError: cannot import name 'OrderedDict'_

Any thoughts about this? 

Jun

**Comment by lizziel** [comment]
Hi Jun, xbcph was updated over the weekend to correct the incompatibility with xarray. This does not explain why you are having issues with xbpch 0.3.4 + xarray 0.11.3, since OrderedDict is include in 0.11.3. However, maybe updating both xbpch and xarray to the latest versions will make the issue moot.

I updated to xbpch 0.3.5 and xarray 0.12.1 and am able to import xbpch successfully. Try this and see if it helps.

```

xarray                    0.12.1                     py_0  
xbpch                     0.3.5                    pypi_0    pypi
xesmf                     0.1.1                    pypi_0    pypi
xlrd                      1.2.0                    py36_0  
xlsxwriter                1.1.2                    py36_0  
xlwings                   0.15.1                   py36_0  
xlwt                      1.2.0            py36h5ad1178_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h0a44026_1  
zict                      0.1.3                    py36_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  
(gcpy)  ~/gc/python/gcpy $ xterm &
[1] 3172
(gcpy)  ~/gc/python/gcpy $ Warning: Color name "black " is not defined
ipython
Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 23 2018, 14:01:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import xarray                                                                     

In [2]: import gcpy                                                                       

In [3]:       
```
