### ISSUE TITLE
[FEATURE REQUEST] Add code to generate plots & tables for 1-year (fullchem) benchmark simulations 

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#41]
## Overview
As of this writing, the following plots & tables for the 1-year (fullchem) benchmarks are currently generated by IDL code.  We would to add this functionality in Python so that we can retire IDL.  As this work progresses we will update this issue in the comments section below.

### Plots:
1. Species concentration by category
2. Emissions by category
3. J-values
4. Column AOD

### Tables:
1. Emission totals table for 1-year benchmark simulations 
2. Inventory totals table for 1-year benchmark simulations
3. Global masses at end of simulation

### Plots
1. Model vs. Observations
2. Aerosol vertical profiles

### Tables
1. Aerosol burdens
2. Global mean AOD
3. O3 STE (vertical flux across 100hPa)

## Related
Please see this issue about work that is being done to migrate the code for plotting results from the 1-year TransportTracers simulation from IDL to Python: https://github.com/geoschem/gcpy/issues/40

**Comment by yantosca** [comment]
We are considering passing SpeciesConc data instead of SpeciesRst data so that we can create annual mean mass tables from 1-year benchmark output.

One sticking point: The function make_benchmark_mass_tables relies on Met_DELPDRY which is only in the restart file but not by default in the StateMet files.  We should add Met_DELPDRY to the StateMet collection in the GC benchmark output.

**Comment by msulprizio** [comment]
> We are considering passing SpeciesConc data instead of SpeciesRst data so that we can create annual mean mass tables from 1-year benchmark output.

We should allow for both options. My understanding is monthly mean concentrations via SpeciesConc would be used for 1-year benchmark output to compute annual mean masses and instantaneous concentrations via SpeciesRst would be used for 1-month benchmarks to compute masses at the end of the simulation. The latter is useful for seeing how mass changes as the result of model updates because all 1-month benchmarks are initialized with the same restart file (i.e. they aren't spun up).

**Comment by yantosca** [comment]
We have now modified GCPy so that you can create benchmark plots & budgets for either the full-chem or TransportTracers benchmarks.

NOTE: Right now the TransportTracers budget code has to be called separately but further modifications can make it be called from run_1yr_benchmark.py.

**Comment by yantosca** [comment]
The following tables are now implemented in GCPy for 1-year FullChemBenchmark outputs:

1. Aerosol burdens
2. Global mean AOD
3. O3 STE (vertical flux across 100hPa

For the time being, the model vs. observations for the 1-year output are still produced in IDL,  pending rewriting of those routines in Python.

**Comment by yantosca** [comment]
I have added a separate feature request (https://github.com/geoschem/gcpy/issues/71) to add the model vs. observations plotting capability in GCPy.

I will now close out this issue, as all of the other 1-year benchmark plottting capabilities are now present in GCPy.
