### ISSUE TITLE
[FEATURE REQUEST] Add species class for GCPy to use generally?

### ISSUE THREAD

**Issue by tsherwen** [geoschem/gcpy#42]
I would be interested in whether GCST/GCPy users thought it would good to have an all-encompassing species class to used and accessible through GCPy?

There is one of these in AC_tools (class species in [AC_tools/variables.py](https://github.com/tsherwen/AC_tools/blob/master/AC_tools/variables.py)), which allows for you access various variables (such as the subset below). These species objects can then be passed to functions and when properties are needed (e.g. what mechanism a species is used within) can be retrieved. 

    specs2use = ['O3', 'ALD2', 'ACET']                                                                                                          
    spec_objs = [AC.species(i) for i in specs2use]                                                                                              
    prt_str = 'Name = {:<5}, RMM: {:.2f}, Drydep: {}, Wetdep: {}, Formula: {}, Ox: {}, LaTeX: {}'    
    for spec in spec_objs: 
        print( prt_str.format( spec.name, spec.RMM, spec.Drydep, spec.Wetdep )  )     
                                                                                                                                             
    Name = O3   , RMM: 48.00, Drydep: True, Wetdep: False, Formula: O3, Ox: 1.0, LaTeX: O$_{3}$
    Name = ALD2 , RMM: 44.05, Drydep: True, Wetdep: True, Formula: CH3CHO, Ox: nan, LaTeX: Acetaldehyde
    Name = ACET , RMM: 58.08, Drydep: True, Wetdep: False, Formula: CH3C(O)CH3, Ox: nan, LaTeX: CH$_{3}$C(O)CH$_{3}$

The properties are currently just generated from the [GEOS-Chem wiki page on species](http://wiki.seas.harvard.edu/geos-chem/index.php/Species_in_GEOS-Chem).  

I saw [the related commit on the GEOS-Chem repository](https://github.com/geoschem/geos-chem/issues/109) and was thinking about updating to use this file when it started being outputted.

**Comment by yantosca** [comment]
Hi Tomas -- thanks for writing.  Right now we get the species properties in GCPy from the species_database.json file (which can be directly generated from GEOS-Chem).    That can be read right into a dictionary.  

```python
    import json

    # Load a JSON file containing species properties (such as
    # molecular weights), which we will need for unit conversions.
    # This is located in the "data" subfolder of this folder where
    # this benchmark.py file is found.
    properties_path = os.path.join(os.path.dirname(__file__),
                                   'species_database.json')
    properties = json.load(open(properties_path))
    . . .
    # Get a list of properties for the given species
    species_properties = properties.get(spc_name)

    # Get a field for each species 
    mol_wt_g = species_properties.get('MW_g')
```

I think it is important to preserve the ability of reading a JSON that is generated by GEOS-Chem, because then that prevents a disconnect between the GC code and the GCPy code.    

Also, up until now we have been trying not to add new classes into GCPy, so as not to proliferate additional classes throughout the code except those that are commonly used (xarray, numpy, etc.).  @JiaweiZhuang had a reference about that but I can't seem to find it now.  Perhaps we can rethink that if need be.

**Comment by yantosca** [comment]
Also, this can be shortened to:
```python
import gcpy
import json
import os
path = os.path.join(os.path.dirname(gcpy.__file__), 'species_database.json')
sd = json.load(open(path))
print(sd.get('O3').get('MW_g'))
48.0
print(sd.get('O3').get('Is_DryDep'))
True
``

**Comment by tsherwen** [comment]
Hello Bob, 

Thanks for getting back to me on this. I totally agree with your take that the data on species properties should be held in a single place in the main code. I will be updating my code to use this json file and would have done that originally if I had been aware of it. I guess the follow on question is then whether it would be useful to have other properties might included in code that the json is generated from (e.g. Ox - & any other [columns in wiki species table](http://wiki.seas.harvard.edu/geos-chem/index.php/Species_in_GEOS-Chem))? 

I did some minor updates to the wiki page on GC species, so I guess this is not automatically generated. Maybe this too could be automatically generated from the json file to keep pace with any changes in the core code?

Cheers, 

Tomas
