### ISSUE TITLE
[BUG/ISSUE] Zonal mean plots with pressure subset are incorrect when y-axis flipped

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#45]
Using the pressure subsetting option in compare_zonal_mean works correctly when the flip_ref and/or flip_dev are set to the default value (False). However, it seems that the plots are not correct if the vertical axis is flipped.

For example, here are concentration plots for Br2 mean full column (no subsetting) with the vertical axis of the Dev data flipped. This is comparing a GCC restart file with a GCHP restart file, so this flipping is necessary.

<img width="1045" alt="Br2_rst_zonal_log_partial" src="https://user-images.githubusercontent.com/651947/67900672-65bc6b00-fb3b-11e9-8807-c56ea1530633.png">

To hone in on the stratosphere I use the pressure subsetting for interval [1,100]. This is what is plotted:
<img width="1024" alt="Br2_rst_zonalstrat_log_partial" src="https://user-images.githubusercontent.com/651947/67900736-8e446500-fb3b-11e9-8088-33204c7267fd.png">

I suspect the issue is the order of the subsetting and the flipping. I will investigate.

**Comment by yantosca** [comment]
I wonder if the 0, 0 is because it is printing integers on the axis.  Maybe it should go like 1, 0.2, 0 or something like that.  You could tweak with the formatter and specify a single decimal space.

**Comment by lizziel** [comment]
See https://github.com/geoschem/gcpy/issues/44 for discussion of the 0, 0.

The pressure subset issue when y-axis flipped is fixed with https://github.com/geoschem/gcpy/commit/e808366a310e8b87950605a97a24a606321516dd.

<img width="1077" alt="Screen Shot 2019-11-04 at 4 36 54 PM" src="https://user-images.githubusercontent.com/651947/68160251-549ba180-ff21-11e9-8150-f2304e890fb5.png">
