### ISSUE TITLE
[BUG/ISSUE] Global mass tables not recognizing new species as missing in reference version

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#47]
The global mass tables in GCPy are not properly recognizing when species are missing from a version. For example, in comparisons of dev/12.7.0 with GEOS-Chem 12.6.0, new species ETNO3, MENO3, IPRNO3, and NPRNO3 are all listed with the values of the previous species in the Ref column when they should be NaN. 

Here is the original message from Jenny Fisher:

>I don’t think the [global mass tables](http://ftp.as.harvard.edu/pub/exchange/mpayer/GC_12.7.0_SmallAlkylNitrateChem/Plots/GC_12.7.0_SmallAlkylNitrateChem_GlobalMass_Trop.txt) are pointing to the right Ref version as they show values for all the new species in the 12.6.0 version.

Here is the problematic text in the global mass tables:
```
###############################################################################
### Global mass (Gg) at end of simulation (Trop only)                       ###
### Ref = GC_12.6.0; Dev = GC_12.7.0_SmallAlkylNitrateChem                  ###
###############################################################################
                              Ref                 Dev      Dev - Ref    % diff
ETHLN        :           0.396240            0.395432      -0.000808    -0.204
ETNO3        :           0.396240           19.799126      19.402885  4896.751
...
IPMN         :          97.114059           96.601143      -0.512917    -0.528
IPRNO3       :          97.114059           26.614943     -70.499115   -72.594
...
MEK          :        2037.818237         2031.013916      -6.804321    -0.334
MENO3        :        2037.818237           48.085583   -1989.732666   -97.640
...
NPMN         :           0.003098            0.003046      -0.000051    -1.661
NPRNO3       :           0.003098            6.418084       6.414987  207093.115
...
```

**Comment by yantosca** [comment]
Does this seem to be fixed now??

**Comment by msulprizio** [comment]
No. See http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_12/12.8.0/GCC/Plots/Tables/GC_12.8.0_GlobalMass_Trop.txt.

Some examples:
```
C3H8         :         714.583008          698.010193     -16.572815    -2.319
C4HVP1       :         714.583008            0.000000    -714.583008  -100.000
C4HVP2       :         714.583008            0.000000    -714.583008  -100.000

HBr          :           2.967226            2.937771      -0.029455    -0.993
HC5A         :           2.967226            4.371144       1.403918    47.314

HI           :           0.305149            0.305817       0.000668     0.219
HMHP         :           0.305149           37.884537      37.579388  12315.103
HMML         :           0.305149           15.414655      15.109506  4951.521
```

where C4HVP1, C4HVP2, HC5A, HMHP, and HMML are new species (i.e. not in Ref).

**Comment by yantosca** [comment]
This is now fixed in commit https://github.com/geoschem/gcpy/commit/c5391a6856dafdc7cf7f8fe7271346caf0cd416d

The fix is that we now have to define the `refarray` and `devarray` variables outside of the if statements where they are checked for all NaNs.

https://github.com/geoschem/gcpy/blob/c5391a6856dafdc7cf7f8fe7271346caf0cd416d/gcpy/benchmark.py#L2435-L2465

This now results in missing variables being printed as NaN's in the mass tables:
```
C3H8         :         728.269592          708.471497     -19.798096    -2.719
C4HVP1       :                nan            0.000004            nan       nan
C4HVP2       :                nan            0.000007            nan       nan
```
