### ISSUE TITLE
gcpy.open_mfdataset won't open .nc4 data

### ISSUE THREAD

**Issue by jmoch1214** [geoschem/gcpy#5]
gcpy.open_mfdataset won't open .nc4 data. Instead it says it needs ".nc"

I think this is a bug since the default GCHP output is now .nc4.

The errors says: "ValueError: Found unknown file extension (.nc4); please pass a BPCH or netCDF file with extension 'bpch' or 'nc'."

**Comment by jmoch1214** [comment]
This is a simple fix.

I added to the core.py under the open_mfdataset function:

    if file_extension == '.bpch':
        _opener = xbpch.open_mfbpchdataset
    elif file_extension == '.nc':
        _opener = xr.open_mfdataset
    **elif file_extension == '.nc4':
        _opener = xr.open_mfdataset**
    else:
        raise ValueError("Found unknown file extension ({}); please pass a "
                         "BPCH or netCDF file with extension 'bpch' or 'nc' **or 'nc4'**."
                         .format(file_extension))

**Comment by lizziel** [comment]
Thanks for submitting this. Your pull request is now merged and this issue is closed.
