### ISSUE TITLE
[FEATURE REQUEST] Store constants used in GCPy in file constants.py

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#50]
Constants used in GCPy are not all in file constants.py, such as values returned by function skip_these_vars(). The package would be improved by keeping all constants in that file for usage elsewhere.

**Comment by yantosca** [comment]
The list of variables to skip (skip_these_vars) is now in constants.py.

**Comment by yantosca** [comment]
The `constants.py` file now contains several physical constants as well as the skip_these_vars list.  This is now used by several other GCPy functions.
