### ISSUE TITLE
[BUG/ISSUE] Empty or unused directories

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#51]
Directory gcpy/obs is effectively empty since it contains file __init__.py with no text. Some other directories contain files that are not used anywhere atm_sci. These could be cleaned up to focus GCPy on functions actively used and supported.

**Comment by WilliamDowns** [comment]
gcpy/obs/ and gcpy/atm_sci/ have both been removed.

**Comment by WilliamDowns** [comment]
Empty directories and unused functions were removed in 0.3.0.
