### ISSUE TITLE
[BUG/ISSUE] Update authors.txt to include contributors to GCPy

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#53]
File authors.txt currently includes all developers who have contributed to GEOS-Chem. The file should instead list all developers who have contributed to GCPy.

**Comment by yantosca** [comment]
This has now been resolved with commit https://github.com/geoschem/gcpy/commit/2ffe6df7bc704422f9452beb1dcf4a3ebcbc867f.
