### ISSUE TITLE
[BUG/ISSUE] ReadTheDocs does not work in GCPy 

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#54]
ReadTheDocs looks like it is supported in GCPy but does not actually work. I have found that building the doc results in an out-of-memory issue. This is possibly due to runnable docstrings that require loading many libraries. If we are not going to support ReadTheDocs in the short-term we should remove code related to it. We can bring it back from the git history in the future if we want to add it back in and get it working.

**Comment by yantosca** [comment]
We have removed runnable docstrings, see commit: https://github.com/geoschem/gcpy/commit/54cab17e1217c4de709254225c447049ca7d3426

At some point we can re-investigate the auto-doc via ReadTheDocs or another option.

**Comment by WilliamDowns** [comment]
A functioning ReadTheDocs site is available as of version 1.0.0.
