### ISSUE TITLE
[BUG/ISSUE] Runnable docstrings for doctest are broken

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#55]
There are several runnable docstrings that can be invoked with doctest. For example:                                                                           
```
    >>> from gcpy import core                                                             
    >>> import xarray as xr                                                               
    >>> ds = xr.open_dataset('myfile.nc', drop_variables=skip_these_vars()) 
```
However, executing the code will not work because dependencies such as datasets or paths are not functional. For example, file myfile.nc used in the above docstring is not included in GCPy. The runnable docstrings should be removed if they are not functional.

**Comment by yantosca** [comment]
I have taken out all of the runnable docstrings from GCPy headers.  See commit https://github.com/geoschem/gcpy/commit/54cab17e1217c4de709254225c447049ca7d3426
