### ISSUE TITLE
[FEATURE REQUEST] Highlight functionality by making locally used functions private

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#57]
Right now nearly all functions are publicly available. This can make it hard to figure out what the main features of gcpy are and how to use them. __init__.py could be updated to selectively make the highest level features of GCPy available publicly visible with tools such as ipython and Jupyter Notebook. This would make browsing the package more simple and informative.

**Comment by yantosca** [comment]
@lizziel: Do you have a sense of which routines should be private?

**Comment by lizziel** [comment]
I'm afraid not. I created this issue 3 years ago when the structure was likely very different from now. I wonder if we should close this.
