### ISSUE TITLE
[DISCUSSION] Style guide planning

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#58]
Eventually we should issue a style guide for GCPy for us and users to follow. Here are some initial ideas to get a conversation going on guidelines to follow, starting now and into the future.

1. Keep docstrings as concise as possible.
2. Do not make functions for low level python, opting instead to use base python directly
3. Make functions, variables, classes etc private unless approved by the team to be public
4. Use auto-formatting and style check tools such as pylint, pycodestyle, and black
5. Keep tests isolated to high-level functions
6. Include all dependencies plus versions in Requirements.txt, and make sure it stays up-to-date with every version
7. Make sure pip install works. GCPy is not available from PyPI or Conda, but cloning it should enable installation via pip

**Comment by lizziel** [comment]
@WilliamDowns, could you comment on how much of this list has already been done?

**Comment by WilliamDowns** [comment]
1. I did not look into this (but did reformat every docstring to match one another).
2. I believe I looked into this briefly. I think things are fine on this front right now.
3. I don't believe anything is currently explicitly private.
4. I definitely used pylint for the 1.0.0 release. I don't remember if I went through with pycodestyle or black. pylint is very useful, and it would be good to define standard options to enable and disable when using pylint.
5. Tests still need to be setup (the few I had created are now very old / incomplete).
6. I have not updated these in a bit. When changing requested dependency versions, make sure to also update the Conda environment files and the Conda install recipe in the conda-forge feedstock.
7. GCPy is now available on conda-forge. You can also install using `pip install` on a local clone using the relevant [instructions in the Read The Docs](https://gcpy.readthedocs.io/en/stable/Getting-Started-with-GCPy.html#installing-gcpy-for-developers).

**Comment by lizziel** [comment]
Thanks!!
