### ISSUE TITLE
[FEATURE REQUEST] Provide two env yaml files: base dependencies and sci env

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#59]
Currently the environment.yml file that ships with GCPy includes a whole lot of packages not used in GCPy. This environment is a recommendation developed a while ago for general scientific computing. It would be useful to also have a base environment yml file with the dependencies needed for GCPy only. We should also revisit the recommended scientific computing environment to make sure we understand it and approve it.

**Comment by WilliamDowns** [comment]
Added in 1.0.0. There are now 3 different environment file folders: 

- `gcpy_min` (all libraries required to run GCPy)
-  `gcpy_full` (same as min + a few useful general Python libraries and tools like Jupyter and iPython)
- `gcpy_extras` (same as full but with added scientific libraries like Tensorflow, Scikit-learn)
