### ISSUE TITLE
[BUG/ISSUE] Requirements.txt used for pip install is out-of-date

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#61]
Several package dependencies for GCPy are not included in file Requirements.txt. This makes installation with pip not work. Ideally users would be able to clone GCPy and install into their existing python environment with pip.

**Comment by lizziel** [comment]
Ideally package number would also being included in Requirements.txt.

**Comment by WilliamDowns** [comment]
`requirements.txt` has been updated with version number requirements as of 1.0.0.
