### ISSUE TITLE
[BUG/ISSUE] Avoid double counting AOD for isoprene SOA in total AOD

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#65]
Total AOD is computed by summing the AOD diagnostics. However, AOD for OCPI already includes the contribution from isoprene SOA. Including both `AODHyg550nm_OCPI` (aka Column_AOD_OCPI) and `AODSOAfromAqIsoprene550nm` (aka Column_AOD_SOA_from_Aqueous_ISOP) in total AOD is therefore double counting the contribution from isoprene SOA.

**Comment by yantosca** [comment]
This is now added in commit https://github.com/geoschem/gcpy/commit/9d378efdb27e09b3d626f2e5082ce55bddeeb207, which will be added to GCPy 0.2.0.
