### ISSUE TITLE
[FEATURE REQUEST] Annual plots produced by 1-year benchmark routines

### ISSUE THREAD

**Issue by tsherwen** [geoschem/gcpy#66]
Please can I request that annual average plots are output for 1-year benchmark runs for each category and also for emissions?

Currently, plots are output Jan, Apr, Jul, and Oct for categories (e.g. Ox, aerosols etc) like in [the 1-year v12.6.0 benchmarks](http://wiki.seas.harvard.edu/geos-chem/index.php/Benchmark/GEOS-Chem_12.6.0#GEOS-Chem_Classic_1-year_benchmark). It would be good to have annual average plots too, as this would be useful as an initial point to look at and get a handle on the 1-year benchmarks. To get an idea of the whole year I am currently opening four sets of plots per category (Jan, Apr, Jul, and Oct)or just choosing a single month to start with. Neither of these seem ideal. What does GCST think? Has this already been discussed/considered?

**Comment by yantosca** [comment]
We will try to add this soon.

**Comment by msulprizio** [comment]
We've recently had the need for this output when examining past 1-year benchmark results. I suggest that we prioritize this feature request for the next GCPy release.

**Comment by yantosca** [comment]
This should be pretty straightforward.  I've added a convenience method to `util.py` to take the mean of a dataset along the time dimension:

https://github.com/geoschem/gcpy/blob/f2fb3750126ec18e4f1fcd4ef9b6026f70a9e07d/gcpy/util.py#L1843-L1872

and then in the methods that create plots (e.g. `make_benchmark_conc_plots`, we just need to run this on datasets before continuing with the plotting, e.g.:

https://github.com/geoschem/gcpy/blob/f2fb3750126ec18e4f1fcd4ef9b6026f70a9e07d/gcpy/benchmark.py#L701-L750

I am working on this in the feature/bmy/annual_mean branch and should have this ready fairly soon (in time for the 13.1.0 benchmarks).

**Comment by yantosca** [comment]
I have updated the following scripts for producing annual mean plots.

  1. gcpy/benchmark.py
  2. gcpy/util.py
  3. benchmark/run_1yr_tt_benchmark.py
  4. benchmark/run_yr_fullchem_benchmark.py
  5. benchmark/run_1mo_benchmark.py
    - This was made consistent with the other benchmark scripts

This has now been pushed into the dev branch of gcpy.  We can release this as gcpy 1.0.4 pending further testing.

**Comment by yantosca** [comment]
This will be introduced into GCPy 1.1.0 instead.  I've updated the milestone.  I think we can close this issue out.
