### ISSUE TITLE
[FEATURE REQUEST] GCHP vs GCC mass tables 

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#67]
**GCPy version**

Branch: `dev/0.2.0`
Commit: 610d365c

**Run script**

[run_1mo_benchmark.py](https://github.com/geoschem/gcpy/files/4394722/run_1mo_benchmark.txt)

**Error message:**

```
%%% Creating GCHP vs. GCC FullChemBenchmark global mass tables %%%
Traceback (most recent call last):
  File "run_1mo_benchmark.py", line 621, in <module>
    overwrite=True)
  File "/n/home05/msulprizio/GC/python/gcpy/gcpy/benchmark.py", line 4388, in make_benchmark_mass_tables
    verbose=verbose,
  File "/n/home05/msulprizio/GC/python/gcpy/gcpy/benchmark.py", line 2437, in create_global_mass_table
    print_totals(refarray, refstr, devarray, devstr, f, mass_tables=True)
UnboundLocalError: local variable 'devarray' referenced before assignment
```

**Comment by lizziel** [comment]
This feature will not be implemented until the needed meteorology fields are included in the GCHP restart file, which will go into 12.9.

**Comment by lizziel** [comment]
I am moving this update up to 12.8.1. Starting in that version GCHP internal state checkpoint files will include tropopause level and box height if running the benchmark or transport tracer simulations. The standard simulation will not included these variables in the internal state, but they can still be accessed via HISTORY collections if needed.

**Comment by WilliamDowns** [comment]
This functionality was added in 0.2.0.
