### ISSUE TITLE
[BUG/ISSUE] Significant differences for J-values and column AOD not printing to file

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#69]
**GCPy version**

Branch: `dev/0.2.0`
Commit: d046db18ad4a00c751dfc0766d34700f28e70796

**Run script**

https://github.com/geoschem/gcpy/blob/dev/0.2.0/benchmark/run_1mo_benchmark.py

**Description of issue:**

In the significant difference file [GCC_ref_vs_GCC_dev_sig_diffs_sfc.txt](https://github.com/geoschem/gcpy/files/4405224/GCC_ref_vs_GCC_dev_sig_diffs_sfc.txt), J-values and Column AOD are returned with blanks leading one to believe there are no significant differences. However, when in Jval_Surface.pdf (file too large to upload) and [Aerosols_ColumnOptDepth.pdf](https://github.com/geoschem/gcpy/files/4405228/Aerosols_ColumnOptDepth.pdf), there are clearly differences > 0.1.

**Comment by WilliamDowns** [comment]
Fixed in dev/0.2.0. Bug resulted from parallel calls within compare_single_level and compare_zonal_mean where sigdiff_list was not properly updated.
