### ISSUE TITLE
[FEATURE REQUEST] Add GCPy routines to plot 1-year model vs. observations

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#71]
Right now the only thing in the GCC vs. GCC 1-year benchmarks that are not plotted by GCPy are the model vs. observation plots.  These continue to be plotted with very old IDL scripts.

We do not have a huge rush to add this new functionality in GCPy, but I am adding this as a feature request for documentation purposes (and as a reminder to add this in the future).

**Comment by yantosca** [comment]
NOTE: The previous feature request for 1-year benchmark output (https://github.com/geoschem/gcpy/issues/41) is now closed

**Comment by jingqiumao** [comment]
Is this feature currently available in GCPy?

**Comment by msulprizio** [comment]
@jingqiumao No. We're still currently using the IDL code currently at https://bitbucket.org/gcst/gc_1yr_benchmark/src/master/. 

The idea was that the GCSC would discuss and contribute to a new set of model vs observation routines in Python. Mat Evans was leading the task, but I don't think there has been any discussion or development in several months.

**Comment by yantosca** [comment]
At the 21 Sep 2022 GCSC meeting, Lu Hu noted that Amy Christiansen is building a new climatology (10-years of ozonesonde data) that will likely allow us to retire the existing dataset.  Hopefully this will also come with python code to plot the data vs. observations.

**Comment by yantosca** [comment]
> At the 21 Sep 2022 GCSC meeting, Lu Hu noted that Amy Christiansen is building a new climatology (10-years of ozonesonde data) that will likely allow us to retire the existing dataset. Hopefully this will also come with python code to plot the data vs. observations.

NOTE: The plotting scripts that go with this dataset are in R, but we need them in Python.

**Comment by jingqiumao** [comment]
Thanks Bob! I am wondering if there is anyone who knows both R and Python can help with this. I chatted with Randall before but am not sure how we can proceed.

Jingqiu

**Comment by yantosca** [comment]
Model vs. sonde plots have been added into GCPy.  These will debut in the 14.4.0 1-year benchmarks.

We can close out this issue now.
