### ISSUE TITLE
[DISCUSSION] GCPy benchmark file organization

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#76]
In updating the GCPy benchmarking tools for GCHP I've had some thoughts on ways we could make storage of the benchmark artifact folders more logical. Here are my thoughts on this:

1. Plots folder contains both plots and tables. Rename it to benchmark type. E.g. instead of Plots/GCC_version_comparison, it would be 1mo_benchmark/GCC_version_comparison. This allows testing gcpy benchmarking with all run scripts in the same folder
 
2. Within that would be two folders: Plots and Tables. This solves the strange logic in there now, such as aerosol burdens table in Tables not Aerosols, but emissions totals in Emissions not Tables.

3. Eventually make all tables be comparisons with ref, def, difference, and % diff. This would make all artificacts in e.g. GCC_version_comparison be comparisons. This avoids having to dig up the last benchmark to see the change.

4. Organize tables by type rather than month. Month folders, e.g. Apr2016, are a mystery about what is inside. Replacing with subfolders such as Seasonal_Global_Mass would make clear what is available.

**Comment by msulprizio** [comment]
I'm all for reorganizing, but I would recommend we think carefully about how to do it so we don't have to keep changing it in the future. Recently, the files were organized into monthly folders, which required updating the 300+ links to those plots on the benchmark wiki pages. To avoid complicating the creation of future benchmark tables on the wiki, I would like to ask that we choose a structure and stick with it.

**Comment by lizziel** [comment]
I totally agree. We've had a somewhat haphazard approach with changing things in GCPy thus far. Moving forward we can have discussions on GCPy for these sorts of changes so we can all contribute to and be aware of decisions before they are made.

**Comment by lizziel** [comment]
Following up on this, I believe @WilliamDowns implemented all of these changes, or some form of them, so that the GCPy benchmark files are better organized. I will close this issue.
