### ISSUE TITLE
[FEATURE REQUEST] Reduce number of times lumped_species.yml and benchmark_species.yml are computed and archived

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#78]
GCPy seems to archive the 'benchmark_species.yml' and 'lumped_species.yml' files more often than necessary. For example, in the 1-year benchmark plots, they're archived at least four times -- once for every benchmark month (Jan, Apr, Jul, Oct).

**Comment by msulprizio** [comment]
Renamed this issue to address the second issue brought up here -- the .yml files may be getting archived more than once.

The original issue -- GCPy stalling after archiving those files -- appears to be a non-issue. The apparent delay in GCPy after printing 
```
Archiving lumped_species.yml in /n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/GC_12.8.0/Plots
Archiving benchmark_categories.yml in /n/holyscratch01/jacob_lab/msulprizio/GC/benchmarks/1mon/GC_12.8.0/Plots
```
is simply when the code is creating the plots and PDF files.

**Comment by msulprizio** [comment]
GCPy still seems to be computing the lumped species and archiving lumped_species.yml and benchmark_species.yml many times while generating benchmark output. Therefore, I am reopening this issue and now making it a feature request to address it.

**Comment by yantosca** [comment]
The quickest way to do this is to not archive the YAML file if it is already on disk.  In util.py:
```python
def archive_species_categories(dst):
    ... docstr omitted ...
    spc_categories = "benchmark_categories.yml"
    src = os.path.join(os.path.dirname(__file__), spc_categories)
    copy = os.path.join(dst, spc_categories)
    if not os.path.exists(copy):
        print("Archiving {} in {}".format(spc_categories, dst))
        shutil.copyfile(src, copy)

def archive_lumped_species_definitions(dst):
    ... docstr omitted ...
    lumped_spc = "lumped_species.yml"
    src = os.path.join(os.path.dirname(__file__), lumped_spc)
    copy = os.path.join(dst, lumped_spc)
    if not os.path.exists(copy):
        print("Archiving {} in {}".format(lumped_spc, dst))
        shutil.copyfile(src, copy)
```
I am testing this now.

**Comment by yantosca** [comment]
This is now done in commit 421ddd39632b3ea4339587192bce468be76060ee.   We can close this issue out.
