### ISSUE TITLE
gcbm does not have plot_layer

### ISSUE THREAD

**Issue by LyssaFreese** [geoschem/gcpy#8]
Right now I keep encountering an attribution error that gcpy.benchmark (gcbm) does not have  plot_layer. I'm working through the first tutorial of benchmark_design.ipynb--does gcbm no longer have the plotting function?

**Comment by yantosca** [comment]
Hi -- we have moved away from the plot_layer function.  See the script gcpy/benchmark/run_1mo_benchmark,py instead.

**Comment by LyssaFreese** [comment]
got it! thank you!
