### ISSUE TITLE
[FEATURE REQUEST] Use separate ref and dev lumped species definition files in benchmarking

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#81]
It would be nice to be able to compare lumped species before and after any changes in constituent species between versions during benchmarking. I propose that we do this by using the Ref version lumped species definition for Ref plots and the Dev version lumped species definition for Dev plots in benchmarks. This will allow side by side comparison of the concentrations without have to refer back to the last benchmark plots.

This could go along with an update to store the lumped species definitions within GEOS-Chem source code rather than GCPy so that it can be updated and tracked alongside chemistry changes. This would also help move towards decoupling GCPy and GEOS-Chem versions.

This update is best put into whatever GCPy version we use for 13.0 benchmark since that GEOS-Chem version will contain run directory files.

**Comment by yantosca** [comment]
@lizziel @msulprizio has this been done in the latest benchmark?  If so we can close it out.

**Comment by lizziel** [comment]
I am revisiting this issue because we are discussing putting a path to the species database in the benchmark yml file. @yantosca, would it be much work (or even worthwhile) to have separate species databased for ref and dev? Maybe it would be more trouble than it is worth?

**Comment by lizziel** [comment]
Actually, I just realized this issue is about lumped species, not the species database.

**Comment by yantosca** [comment]
@lizziel, we could specify ref & dev species database or lumped_species.  We'd need to add a lumped_species.yml to the run directories, though.
