### ISSUE TITLE
[FEATURE REQUEST] Add MCF and CH4 lifetimes to 1-year benchmark output

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#84]
The MCF and CH4 lifetimes are included in the [OH metrics output](http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_12/12.8.0/GCC/Plots/Tables/GC_12.8.0_OH_metrics.txt) for the 1-month benchmark. This feature should also be expanded to the 1-year benchmarks.

**Comment by yantosca** [comment]
This is now done, and was used for the [13.0.0 1-year benchmarks](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/13.0.0-beta.1/GCClassic/FullChem/BenchmarkResults/Tables/OH_metrics.txt).
