### ISSUE TITLE
[BUG/ISSUE] GCHP budget tables take much longer than GCC budget tables

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#85]
In GCPy branch dev/0.3.0 the GCHP vs GCC and GCHP vs GCHP budget operations table generation for the 1-month benchmark takes over an hour. The GCC vs GCC tables, however, take around 10 minutes. The budget operations table code needs to be examined for performance bottlenecks when GCHP data is used.

**Comment by WilliamDowns** [comment]
This performance issue was resolved by the new budget operations function added in 0.3.0.
