### ISSUE TITLE
Pick a license.  Any license

### ISSUE THREAD

**Issue by ebo** [geoschem/gcpy#9]
Believe it or not, by not picking and documenting what licences you are releasing the code under can cause people legal trouble.  See:

https://blog.codinghorror.com/pick-a-license-any-license/

Sorry to bring it up, but once I saw that you do not have any license I cannot even really look at it...

**Comment by yantosca** [comment]
Thanks.  We do use the MIT license for GEOS-Chem and related software.  We will make sure to apply the MIT license to GCPy as well.

**Comment by ebo** [comment]
On Jul 24 2019 8:31 AM, Bob Yantosca wrote:
> Thanks.  We do use the MIT license for GEOS-Chem and related
> software.  We will make sure to apply the MIT license to GCPy as 
> well.

Excellent!  Probably the minimum that needs to be done is a copyright 
file and update the github readme to show the license, but to be 
pedantic, adding the copyright to the header of every file is likely a 
good plan.

Thanks for letting me know that this is in the works.

**Comment by yantosca** [comment]
I just pushed the MIT license files and updated the README.rst in the Github folder.  That should be OK for now.  We may add the copyrights later.
