### ISSUE TITLE
[BUG/ISSUE] Silent plotting bug in 0.3.1 when using Cartopy 0.18.0

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#90]
The Support Team has generally been testing GCPy with Cartopy 0.17.0 or earlier. Last week I upgraded to 0.18.0 and noticed that it caused a silent bug in benchmark plotting of GEOS-Chem Classic datasets. The data is flipped latitudinally across the equator. The issue does not occur for GCHP data, as show here for surface ozone:
<img width="1358" alt="Screen Shot 2020-08-21 at 10 37 22 AM" src="https://user-images.githubusercontent.com/651947/91050942-656eee00-e5ed-11ea-905f-935b23842d73.png">

In the recent dev/0.3.1 release @WilliamDowns updated the `environment.yml` file to explicitly attach version numbers to each python package dependency. This includes using Cartopy 0.17.0. If you are using a different set of versions and see flipping across the equator then check your Cartopy version and downgrade to 0.17.0. Better yet, use the 0.3.1 `environment.yml` file included in the source code to create a new python environment with a full set of dependencies known to work.

We will look into a fix to allow upgrade to Cartopy 0.18.0 without the flipping issue.

**Comment by LiamBindle** [comment]
Fixed by #94. We should prefer `pcolormesh()` over `imshow()` since `imshow()` doesn't consider the data's coordinates.

**Comment by lizziel** [comment]
I believe I switched plotting over to imshow from pcolormesh in early 2018 since it was much faster for pdf generation during benchmarking. We should check if there is still a performance bottleneck.

**Comment by LiamBindle** [comment]
pcolormesh is quite a bit slower than imshow(). I suspect it hasn't gotten faster in recent versions. Is the performance of plotting a concern? If so, imshow() is the right way to go. The assumed orientation of the 2d array will just need attention.

**Comment by WilliamDowns** [comment]
I'll do some performance tests, but if `pcolormesh()` is still notably slower then I agree that `imshow()` is the best way to go and will get it working properly. Note that `imshow()` is/was only used for lat/lon single level plotting.

**Comment by lizziel** [comment]
Maybe we could have a toggle for which to use. pcolormesh for papers and imshow for benchmarks.

**Comment by lizziel** [comment]
To be clear, I am assuming there is an accuracy vs performance trade-off going on between imshow and pcolormesh. If accuracy is needed for benchmarks at the cost of speed, it would still be nice to have a fast option for our internal benchmarking of GEOS-Chem.

**Comment by WilliamDowns** [comment]
`imshow()` and `pcolormesh()` are both available for use when plotting lat/lon data via the ``ll_plot_func`` keyword argument in version 1.0.0. `imshow()` is considerably faster but is usually slightly offset from the actual grid of input data, while `pcolormesh()` is slower but spatially accurate.
