### ISSUE TITLE
[FEATURE REQUEST] Table of global mass time series calculated from restarts

### ISSUE THREAD

**Issue by lizziel** [geoschem/gcpy#93]
GEOS-Chem used to have a mass conservation output capability where global mass was calculated online for a given tracer and output to a text file for inspection. This was used in the Transport Tracer benchmarking (GC-Classic only) to check on the mass conservation of a passive tracer. However, this option was removed in 12.8.0 and the table is no longer included in Transport Tracer benchmarks.

A replacement could be to create a mass time series table using output restart files as part of GCPy benchmarking. The benchmarks include mass tables with global mass of each species calculated from the restart file. We could add functionality for a new table that takes a series of restart files, calculates the global mass for a single tracer, and outputs the time series to a text file for validation of global mass fluctuation within the model. This would be useful for benchmarking as well as validation during development, e.g. outputting daily GCHP checkpoint files and then generating the global mass time series from them to check mass conservation of a passive tracer.

@WilliamDowns, please correct me if I am wrong that this does not already exist. If not, since 1.0 is nearing readiness for release it could go into the version following it as time permits.

**Comment by lizziel** [comment]
This is what I have in mind: http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/GC_12/12.2.0/TransportTracers/output/GC_12.2.0-TransportTracers.passive_mass.txt. I believe this was created using the old IDL benchmarking code.

**Comment by WilliamDowns** [comment]
This definitely does not already exist within GCPy and should be pretty straightforward to replicate. 1.1.0 sounds like a good target.
