### ISSUE TITLE
tab in environment.yml

### ISSUE THREAD

**Issue by barronh** [geoschem/gcpy#95]
## Describe the bug

There is a tab on the joblib package line of the environment.yml. On readhat linux with conda 4.7.10, this throws an error. Easy fix, replace tab with spaces.

## To Reproduce

```
$ conda env create --prefix /work/ROMO/anaconda_envs/geoschem --file docs/environment.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "/usr/local/apps/anaconda/2019.07/anaconda3/lib/python3.7/site-packages/c onda/exceptions.py", line 1062, in __call__
     ...
    ruamel_yaml.scanner.ScannerError: while scanning for the next token
    found character '\t' that cannot start any token
      in "<unicode string>", line 39, column 1:
                - joblib=0.15.1# Parallel proce ...
        ^ (line: 39)
```
 
## Expected behavior

Expected installation, got error. Fixed by replacing tab with spaces.

## Required information:

Cannot report version.

**Comment by WilliamDowns** [comment]
Thanks for finding this, this is fixed now in `dev/1.0.0` in 1a079dd26c882ea6a54a37c7019b7b77dbb01e20.
