### ISSUE TITLE
[FEATURE REQUEST] installation should include colormaps

### ISSUE THREAD

**Issue by barronh** [geoschem/gcpy#96]
## Add your feature request below:

Right now, I installed pip and the colormaps directory was omitted. This can be fixed by editing setup.py file in the root of the repository.

```
$ git clone https://github.com/geoschem/gcpy.git           
$ cd gcpy
$ python setup.py install
$ ls /work/ROMO/anaconda_envs/geoschem/lib/python3.6/site-packages/gcpy-0.1.1.dev_73e0792-py3.6.egg/gcpy/
__init__.py   budget_aer.py  grid.py               regrid.py    units.py
__pycache__   budget_tt.py   mean_oh_from_logs.py  ste_flux.py  util.py
benchmark.py  constants.py   plot.py               tests        version.py
```

Note that `colormaps` is missing.

In setup.py, change `package_data = {},` to `package_data = {'gcpy': ['colormaps/WhGrYlRd.txt']},`

```
ls /work/ROMO/anaconda_envs/geoschem/lib/python3.6/site-packages/gcpy-0.1.1.dev_73e0792-py3.6.egg/gcpy/
__init__.py   budget_aer.py  constants.py          plot.py      tests     version.py
__pycache__   budget_tt.py   grid.py               regrid.py    units.py
benchmark.py  colormaps      mean_oh_from_logs.py  ste_flux.py  util.py

```

Now `colormaps` is there. 

Not sure if you also need a MANIFEST.in for sdist, but this is solved simply.

cat << EOF > MANIFEST.in
recursive-include gcpy *.txt
EOF

**Comment by WilliamDowns** [comment]
Thanks for pointing this out. `setup.py` has been neglected for a little while but will be fully functional for the 1.0.0 release (a version with the intent of testing pip is installable through `pip install --extra-index-url https://test.pypi.org/simple/ geoschem-gcpy` or through the just-pushed `feature/PyPi` branch).

**Comment by yantosca** [comment]
In GCPy 1.3.3+ we no longer install GCPy via pip or conda-forge.  See the new https://gcpy.readthedocs.io for updated installation instructions.
