### ISSUE TITLE
[BUG/ISSUE] Unstack operation in reformat_dims is extremely slow

### ISSUE THREAD

**Issue by WilliamDowns** [geoschem/gcpy#98]
The `xarray.Dataset.unstack()` operation in `reformat_dims()` (now located in `regrid.py`) is extremely slow for some reason. I believe I've narrowed the hanging down to a call to `operator.getitem()` in xarray's `backends/netCDF4_.py`, which takes upwards of 30 seconds for each data variable (e.g. each species) in the xarray Dataset on which `unstack()` is called. I've reproduced this issue on Harvard's Cannon cluster as well as an AWS EC2 instance. Updating to the latest versions of xarray, numpy, and pandas does not fix the issue. I can open an issue on xarray's page but would like to hear any feedback here first @LiamBindle. 

One solution I've been tinkering with is using `numpy.reshape()` to reshape the data within each DataArray and copying the reshaped data + new dimension names + all old metadata to a new DataArray, but this shouldn't be needed if `unstack()` would work properly. 

I used the c90 full chemistry restart file for testing. My main command for testing has been:

``` 
python -m gcpy.cs_regrid -i initial_GEOSChem_rst.c90_fullchem.nc -o regridded_s24.nc --sg_params_out 4.0 250 40 --cs_res_out 24 --dim_format_in checkpoint --dim_format_out checkpoint
```

**Comment by LiamBindle** [comment]
Hi Will, 

Yeah, that's problematic. This sounds like what Lizzie must have been running into here: https://github.com/geoschem/gcpy/pull/88#issuecomment-673130858. Unfortunately, I don't have any insite on this, and I wasn't able to reproduce it on Compute1 or my local machine. 

A couple things come to mind:
- What restart file is initial_GEOSChem_rst.c90_fullchem.nc? I'm pretty sure I've tried it with the v2016-07 restart file for standard chemistry. I'm wondering if something like the order of dimensions on disk is different between the files we're testing, and that's leading to the slow down.
- Does calling `load()` on your dataset, prior to doing anything on it help? See http://xarray.pydata.org/en/stable/generated/xarray.Dataset.load.html
- Perhaps this is a useful thread: https://github.com/pydata/xarray/issues/1560

Let me know what you think. I hope we can track down a solution of this.

**Comment by WilliamDowns** [comment]
Thanks Liam. Looks like `load()` does the trick. Will look into other places in the code that might be useful.
