### ISSUE TITLE
[FEATURE REQUEST] Add benchmark script for OH metrics

### ISSUE THREAD

**Issue by yantosca** [geoschem/gcpy#99]
We have added a new benchmarking script `gcpy/oh_metrics.py` that prints the mean OH concentration, MCF lifetime, and CH4 lifetime from the new Metrics collection in HISTORY output.  
```
###############################################################################
### OH Metrics
### Ref = std_merra2_ref; Dev = std_merra2_dev
###############################################################################

------------------------------------------------------------
Global mass-weighted OH concentration [10^5 molec cm^-3]
------------------------------------------------------------
Ref      : 11.75773978682
Dev      : 11.75294415448
Abs diff :  0.00479563233
%   diff :  0.040787

------------------------------------------------------------
CH3CCl3 (aka MCF) lifetime w/r/t tropospheric OH [years]
------------------------------------------------------------
Ref      :  5.290047
Dev      :  5.291457
Abs diff : -0.001409
%   diff : -0.026640

------------------------------------------------------------
CH4 lifetime w/r/t tropospheric OH [years]
------------------------------------------------------------
Ref      :  8.921115
Dev      :  8.923536
Abs diff : -0.001409
%   diff : -0.015797
```
NOTE: The new `oh_metrics.py` script will work only for GEOS-Chem 13.0.0 and newer versions, because older versions do not have the Metrics collection.  When comparing e.g. 12.9.0 to 13.0.0 benchmarks, we may have to rely on the older OH metrics computation.

**Comment by yantosca** [comment]
This script oh_metrics.py is now being used for benchmark comparisons.

**Comment by msulprizio** [comment]
@yantosca Does this also work for 1-year benchmarks? We will need this capability for the GEOS-Chem 13.0.0 1-year benchmarks.

**Comment by yantosca** [comment]
It should.  I used xr.open_mfdataset to read data.  Should be able to find all Metrics files in OutputDir
